--
-- PostgreSQL database dump
--

-- Dumped from database version 14.9
-- Dumped by pg_dump version 16.0

-- Started on 2024-07-11 11:09:33 EEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "DAPP";
--
-- TOC entry 3724 (class 1262 OID 85855)
-- Name: DAPP; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "DAPP" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.UTF-8';


ALTER DATABASE "DAPP" OWNER TO postgres;

\connect "DAPP"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3725 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 85892)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 85891)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 85861)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 85905)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 85904)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 85917)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 85929)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 85946)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 85868)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 85876)
-- Name: Interests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Interests" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Interests" OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 85875)
-- Name: Interests_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Interests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Interests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 85884)
-- Name: LifeStyles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LifeStyles" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."LifeStyles" OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 85883)
-- Name: LifeStyles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LifeStyles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LifeStyles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 85997)
-- Name: LiveStreamParticipants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LiveStreamParticipants" (
    "LiveStreamId" integer NOT NULL,
    "UserId" text NOT NULL,
    "IsInterested" boolean NOT NULL,
    "Attended" boolean NOT NULL,
    "AttendedFromTime" timestamp with time zone,
    "AttendedToTime" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."LiveStreamParticipants" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 85959)
-- Name: LiveStreams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LiveStreams" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "HasStarted" boolean NOT NULL,
    "ScheduledAt" timestamp with time zone,
    "FinishedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UserId" text
);


ALTER TABLE public."LiveStreams" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 85958)
-- Name: LiveStreams_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LiveStreams" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LiveStreams_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 85972)
-- Name: Media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Media" (
    "Id" integer NOT NULL,
    "Url" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "MediaType" integer NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."Media" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 85971)
-- Name: Media_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Media" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Media_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 86014)
-- Name: UserProfileInterests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserProfileInterests" (
    "UserProfileId" integer NOT NULL,
    "InterestId" integer NOT NULL
);


ALTER TABLE public."UserProfileInterests" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 86029)
-- Name: UserProfileLifeStyles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserProfileLifeStyles" (
    "UserProfileId" integer NOT NULL,
    "LifeStyleId" integer NOT NULL
);


ALTER TABLE public."UserProfileLifeStyles" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 85985)
-- Name: UserProfiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserProfiles" (
    "Id" integer NOT NULL,
    "Bio" text NOT NULL,
    "Height" numeric(3,2) NOT NULL,
    "RelationshipGoal" text NOT NULL,
    "Education" text NOT NULL,
    "Zodiac" text NOT NULL,
    "LoveStyle" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."UserProfiles" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 85984)
-- Name: UserProfiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserProfiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserProfiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 85856)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3704 (class 0 OID 85892)
-- Dependencies: 217
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3697 (class 0 OID 85861)
-- Dependencies: 210
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetRoles" VALUES ('b8224407-3f39-49b0-8561-d44f09bb40c6', 'Admin', 'ADMIN', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetRoles" VALUES ('cf815597-a8db-433c-a9e3-a39978c8ac0a', 'User', 'USER', NULL) ON CONFLICT DO NOTHING;


--
-- TOC entry 3706 (class 0 OID 85905)
-- Dependencies: 219
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3707 (class 0 OID 85917)
-- Dependencies: 220
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3708 (class 0 OID 85929)
-- Dependencies: 221
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3709 (class 0 OID 85946)
-- Dependencies: 222
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3698 (class 0 OID 85868)
-- Dependencies: 211
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3700 (class 0 OID 85876)
-- Dependencies: 213
-- Data for Name: Interests; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Interests" VALUES (1, 'Travel', '2024-07-11 11:03:25.94144+03', '2024-07-11 11:03:25.94144+03') ON CONFLICT DO NOTHING;
INSERT INTO public."Interests" VALUES (2, 'Cooking', '2024-07-11 11:03:25.94144+03', '2024-07-11 11:03:25.94144+03') ON CONFLICT DO NOTHING;
INSERT INTO public."Interests" VALUES (3, 'Sports', '2024-07-11 11:03:25.94144+03', '2024-07-11 11:03:25.94144+03') ON CONFLICT DO NOTHING;
INSERT INTO public."Interests" VALUES (4, 'Music', '2024-07-11 11:03:25.94144+03', '2024-07-11 11:03:25.94144+03') ON CONFLICT DO NOTHING;
INSERT INTO public."Interests" VALUES (5, 'Movies', '2024-07-11 11:03:25.94144+03', '2024-07-11 11:03:25.94144+03') ON CONFLICT DO NOTHING;


--
-- TOC entry 3702 (class 0 OID 85884)
-- Dependencies: 215
-- Data for Name: LifeStyles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."LifeStyles" VALUES (1, 'Smoking', '2024-07-11 11:03:25.941442+03', '2024-07-11 11:03:25.941442+03') ON CONFLICT DO NOTHING;
INSERT INTO public."LifeStyles" VALUES (2, 'Workout', '2024-07-11 11:03:25.941442+03', '2024-07-11 11:03:25.941442+03') ON CONFLICT DO NOTHING;
INSERT INTO public."LifeStyles" VALUES (3, 'Drinking', '2024-07-11 11:03:25.941442+03', '2024-07-11 11:03:25.941442+03') ON CONFLICT DO NOTHING;
INSERT INTO public."LifeStyles" VALUES (4, 'Pets', '2024-07-11 11:03:25.941442+03', '2024-07-11 11:03:25.941442+03') ON CONFLICT DO NOTHING;


--
-- TOC entry 3716 (class 0 OID 85997)
-- Dependencies: 229
-- Data for Name: LiveStreamParticipants; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3711 (class 0 OID 85959)
-- Dependencies: 224
-- Data for Name: LiveStreams; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3713 (class 0 OID 85972)
-- Dependencies: 226
-- Data for Name: Media; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3717 (class 0 OID 86014)
-- Dependencies: 230
-- Data for Name: UserProfileInterests; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3718 (class 0 OID 86029)
-- Dependencies: 231
-- Data for Name: UserProfileLifeStyles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3715 (class 0 OID 85985)
-- Dependencies: 228
-- Data for Name: UserProfiles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3696 (class 0 OID 85856)
-- Dependencies: 209
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20240711080326_init', '8.0.6') ON CONFLICT DO NOTHING;


--
-- TOC entry 3727 (class 0 OID 0)
-- Dependencies: 216
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3728 (class 0 OID 0)
-- Dependencies: 218
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3729 (class 0 OID 0)
-- Dependencies: 212
-- Name: Interests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Interests_Id_seq"', 6, false);


--
-- TOC entry 3730 (class 0 OID 0)
-- Dependencies: 214
-- Name: LifeStyles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LifeStyles_Id_seq"', 5, false);


--
-- TOC entry 3731 (class 0 OID 0)
-- Dependencies: 223
-- Name: LiveStreams_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LiveStreams_Id_seq"', 1, false);


--
-- TOC entry 3732 (class 0 OID 0)
-- Dependencies: 225
-- Name: Media_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Media_Id_seq"', 1, false);


--
-- TOC entry 3733 (class 0 OID 0)
-- Dependencies: 227
-- Name: UserProfiles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserProfiles_Id_seq"', 1, false);


--
-- TOC entry 3512 (class 2606 OID 85898)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3500 (class 2606 OID 85867)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3515 (class 2606 OID 85911)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3518 (class 2606 OID 85923)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3521 (class 2606 OID 85935)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3523 (class 2606 OID 85952)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3504 (class 2606 OID 85874)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3507 (class 2606 OID 85882)
-- Name: Interests PK_Interests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Interests"
    ADD CONSTRAINT "PK_Interests" PRIMARY KEY ("Id");


--
-- TOC entry 3509 (class 2606 OID 85890)
-- Name: LifeStyles PK_LifeStyles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LifeStyles"
    ADD CONSTRAINT "PK_LifeStyles" PRIMARY KEY ("Id");


--
-- TOC entry 3535 (class 2606 OID 86003)
-- Name: LiveStreamParticipants PK_LiveStreamParticipants; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LiveStreamParticipants"
    ADD CONSTRAINT "PK_LiveStreamParticipants" PRIMARY KEY ("LiveStreamId", "UserId");


--
-- TOC entry 3526 (class 2606 OID 85965)
-- Name: LiveStreams PK_LiveStreams; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LiveStreams"
    ADD CONSTRAINT "PK_LiveStreams" PRIMARY KEY ("Id");


--
-- TOC entry 3529 (class 2606 OID 85978)
-- Name: Media PK_Media; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Media"
    ADD CONSTRAINT "PK_Media" PRIMARY KEY ("Id");


--
-- TOC entry 3538 (class 2606 OID 86018)
-- Name: UserProfileInterests PK_UserProfileInterests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfileInterests"
    ADD CONSTRAINT "PK_UserProfileInterests" PRIMARY KEY ("UserProfileId", "InterestId");


--
-- TOC entry 3541 (class 2606 OID 86033)
-- Name: UserProfileLifeStyles PK_UserProfileLifeStyles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfileLifeStyles"
    ADD CONSTRAINT "PK_UserProfileLifeStyles" PRIMARY KEY ("UserProfileId", "LifeStyleId");


--
-- TOC entry 3532 (class 2606 OID 85991)
-- Name: UserProfiles PK_UserProfiles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfiles"
    ADD CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id");


--
-- TOC entry 3498 (class 2606 OID 85860)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3502 (class 1259 OID 86049)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3510 (class 1259 OID 86044)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3513 (class 1259 OID 86046)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3516 (class 1259 OID 86047)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3519 (class 1259 OID 86048)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3533 (class 1259 OID 86051)
-- Name: IX_LiveStreamParticipants_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LiveStreamParticipants_UserId" ON public."LiveStreamParticipants" USING btree ("UserId");


--
-- TOC entry 3524 (class 1259 OID 86052)
-- Name: IX_LiveStreams_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LiveStreams_UserId" ON public."LiveStreams" USING btree ("UserId");


--
-- TOC entry 3527 (class 1259 OID 86053)
-- Name: IX_Media_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Media_UserId" ON public."Media" USING btree ("UserId");


--
-- TOC entry 3536 (class 1259 OID 86054)
-- Name: IX_UserProfileInterests_InterestId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserProfileInterests_InterestId" ON public."UserProfileInterests" USING btree ("InterestId");


--
-- TOC entry 3539 (class 1259 OID 86055)
-- Name: IX_UserProfileLifeStyles_LifeStyleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserProfileLifeStyles_LifeStyleId" ON public."UserProfileLifeStyles" USING btree ("LifeStyleId");


--
-- TOC entry 3530 (class 1259 OID 86056)
-- Name: IX_UserProfiles_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UserProfiles_UserId" ON public."UserProfiles" USING btree ("UserId");


--
-- TOC entry 3501 (class 1259 OID 86045)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3505 (class 1259 OID 86050)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3542 (class 2606 OID 85899)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3543 (class 2606 OID 85912)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3544 (class 2606 OID 85924)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3545 (class 2606 OID 85936)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3546 (class 2606 OID 85941)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3547 (class 2606 OID 85953)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3551 (class 2606 OID 86004)
-- Name: LiveStreamParticipants FK_LiveStreamParticipants_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LiveStreamParticipants"
    ADD CONSTRAINT "FK_LiveStreamParticipants_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3552 (class 2606 OID 86009)
-- Name: LiveStreamParticipants FK_LiveStreamParticipants_LiveStreams_LiveStreamId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LiveStreamParticipants"
    ADD CONSTRAINT "FK_LiveStreamParticipants_LiveStreams_LiveStreamId" FOREIGN KEY ("LiveStreamId") REFERENCES public."LiveStreams"("Id") ON DELETE CASCADE;


--
-- TOC entry 3548 (class 2606 OID 85966)
-- Name: LiveStreams FK_LiveStreams_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LiveStreams"
    ADD CONSTRAINT "FK_LiveStreams_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 3549 (class 2606 OID 85979)
-- Name: Media FK_Media_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Media"
    ADD CONSTRAINT "FK_Media_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3553 (class 2606 OID 86019)
-- Name: UserProfileInterests FK_UserProfileInterests_Interests_InterestId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfileInterests"
    ADD CONSTRAINT "FK_UserProfileInterests_Interests_InterestId" FOREIGN KEY ("InterestId") REFERENCES public."Interests"("Id") ON DELETE CASCADE;


--
-- TOC entry 3554 (class 2606 OID 86024)
-- Name: UserProfileInterests FK_UserProfileInterests_UserProfiles_UserProfileId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfileInterests"
    ADD CONSTRAINT "FK_UserProfileInterests_UserProfiles_UserProfileId" FOREIGN KEY ("UserProfileId") REFERENCES public."UserProfiles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3555 (class 2606 OID 86034)
-- Name: UserProfileLifeStyles FK_UserProfileLifeStyles_LifeStyles_LifeStyleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfileLifeStyles"
    ADD CONSTRAINT "FK_UserProfileLifeStyles_LifeStyles_LifeStyleId" FOREIGN KEY ("LifeStyleId") REFERENCES public."LifeStyles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3556 (class 2606 OID 86039)
-- Name: UserProfileLifeStyles FK_UserProfileLifeStyles_UserProfiles_UserProfileId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfileLifeStyles"
    ADD CONSTRAINT "FK_UserProfileLifeStyles_UserProfiles_UserProfileId" FOREIGN KEY ("UserProfileId") REFERENCES public."UserProfiles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3550 (class 2606 OID 85992)
-- Name: UserProfiles FK_UserProfiles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfiles"
    ADD CONSTRAINT "FK_UserProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3726 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2024-07-11 11:09:33 EEST

--
-- PostgreSQL database dump complete
--

