/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { QuestionCategory, QuestionCategoryDto, QuestionCategoryDtoListApiResponse } from '../models/index';
export interface ApiQuestionCategoryIdDeleteRequest {
    id: number;
}
export interface ApiQuestionCategoryIdGetRequest {
    id: number;
}
export interface ApiQuestionCategoryIdPutRequest {
    id: number;
    questionCategoryDto?: QuestionCategoryDto;
}
export interface ApiQuestionCategoryPostRequest {
    questionCategoryDto?: QuestionCategoryDto;
}
/**
 *
 */
export declare class QuestionCategoriesApi extends runtime.BaseAPI {
    /**
     */
    apiQuestionCategoryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuestionCategoryDtoListApiResponse>>;
    /**
     */
    apiQuestionCategoryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuestionCategoryDtoListApiResponse>;
    /**
     */
    apiQuestionCategoryIdDeleteRaw(requestParameters: ApiQuestionCategoryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     */
    apiQuestionCategoryIdDelete(requestParameters: ApiQuestionCategoryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
    /**
     */
    apiQuestionCategoryIdGetRaw(requestParameters: ApiQuestionCategoryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuestionCategory>>;
    /**
     */
    apiQuestionCategoryIdGet(requestParameters: ApiQuestionCategoryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuestionCategory>;
    /**
     */
    apiQuestionCategoryIdPutRaw(requestParameters: ApiQuestionCategoryIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     */
    apiQuestionCategoryIdPut(requestParameters: ApiQuestionCategoryIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
    /**
     */
    apiQuestionCategoryPostRaw(requestParameters: ApiQuestionCategoryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuestionCategory>>;
    /**
     */
    apiQuestionCategoryPost(requestParameters?: ApiQuestionCategoryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuestionCategory>;
}
