/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { CreateRoomParticipantDto, RoomParticipantDtoApiResponse, UpdateRoomParticipantDto } from '../models/index';
export interface ApiRoomParticipantIdPutRequest {
    id: number;
    updateRoomParticipantDto?: UpdateRoomParticipantDto;
}
export interface ApiRoomParticipantLeaveIdPutRequest {
    id: number;
}
export interface ApiRoomParticipantPostRequest {
    createRoomParticipantDto?: CreateRoomParticipantDto;
}
/**
 *
 */
export declare class RoomParticipantApi extends runtime.BaseAPI {
    /**
     */
    apiRoomParticipantIdPutRaw(requestParameters: ApiRoomParticipantIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomParticipantDtoApiResponse>>;
    /**
     */
    apiRoomParticipantIdPut(requestParameters: ApiRoomParticipantIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomParticipantDtoApiResponse>;
    /**
     */
    apiRoomParticipantLeaveIdPutRaw(requestParameters: ApiRoomParticipantLeaveIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomParticipantDtoApiResponse>>;
    /**
     */
    apiRoomParticipantLeaveIdPut(requestParameters: ApiRoomParticipantLeaveIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomParticipantDtoApiResponse>;
    /**
     */
    apiRoomParticipantPostRaw(requestParameters: ApiRoomParticipantPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomParticipantDtoApiResponse>>;
    /**
     */
    apiRoomParticipantPost(requestParameters?: ApiRoomParticipantPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomParticipantDtoApiResponse>;
}
