/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomContentDto } from './RoomContentDto';
import {
    RoomContentDtoFromJSON,
    RoomContentDtoFromJSONTyped,
    RoomContentDtoToJSON,
} from './RoomContentDto';

/**
 * 
 * @export
 * @interface RoomContentDtoListApiResponse
 */
export interface RoomContentDtoListApiResponse {
    /**
     * 
     * @type {number}
     * @memberof RoomContentDtoListApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof RoomContentDtoListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<RoomContentDto>}
     * @memberof RoomContentDtoListApiResponse
     */
    data?: Array<RoomContentDto> | null;
}

/**
 * Check if a given object implements the RoomContentDtoListApiResponse interface.
 */
export function instanceOfRoomContentDtoListApiResponse(value: object): value is RoomContentDtoListApiResponse {
    return true;
}

export function RoomContentDtoListApiResponseFromJSON(json: any): RoomContentDtoListApiResponse {
    return RoomContentDtoListApiResponseFromJSONTyped(json, false);
}

export function RoomContentDtoListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomContentDtoListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RoomContentDtoFromJSON)),
    };
}

export function RoomContentDtoListApiResponseToJSON(value?: RoomContentDtoListApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RoomContentDtoToJSON)),
    };
}

