/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSimplifiedDto } from './UserSimplifiedDto';
import {
    UserSimplifiedDtoFromJSON,
    UserSimplifiedDtoFromJSONTyped,
    UserSimplifiedDtoToJSON,
} from './UserSimplifiedDto';
import type { RoomStatus } from './RoomStatus';
import {
    RoomStatusFromJSON,
    RoomStatusFromJSONTyped,
    RoomStatusToJSON,
} from './RoomStatus';
import type { RoomParticipant } from './RoomParticipant';
import {
    RoomParticipantFromJSON,
    RoomParticipantFromJSONTyped,
    RoomParticipantToJSON,
} from './RoomParticipant';

/**
 * 
 * @export
 * @interface RoomDto
 */
export interface RoomDto {
    /**
     * 
     * @type {number}
     * @memberof RoomDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    description?: string | null;
    /**
     * 
     * @type {any}
     * @memberof RoomDto
     */
    offers?: any | null;
    /**
     * 
     * @type {RoomStatus}
     * @memberof RoomDto
     */
    status?: RoomStatus;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    scheduledAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    finishedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {UserSimplifiedDto}
     * @memberof RoomDto
     */
    user?: UserSimplifiedDto;
    /**
     * 
     * @type {Array<RoomParticipant>}
     * @memberof RoomDto
     */
    roomParticipants?: Array<RoomParticipant> | null;
}

/**
 * Check if a given object implements the RoomDto interface.
 */
export function instanceOfRoomDto(value: object): value is RoomDto {
    return true;
}

export function RoomDtoFromJSON(json: any): RoomDto {
    return RoomDtoFromJSONTyped(json, false);
}

export function RoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'offers': json['offers'] == null ? undefined : json['offers'],
        'status': json['status'] == null ? undefined : RoomStatusFromJSON(json['status']),
        'scheduledAt': json['scheduledAt'] == null ? undefined : (new Date(json['scheduledAt'])),
        'finishedAt': json['finishedAt'] == null ? undefined : (new Date(json['finishedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'user': json['user'] == null ? undefined : UserSimplifiedDtoFromJSON(json['user']),
        'roomParticipants': json['roomParticipants'] == null ? undefined : ((json['roomParticipants'] as Array<any>).map(RoomParticipantFromJSON)),
    };
}

export function RoomDtoToJSON(value?: RoomDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'offers': value['offers'],
        'status': RoomStatusToJSON(value['status']),
        'scheduledAt': value['scheduledAt'] == null ? undefined : ((value['scheduledAt'] as any).toISOString()),
        'finishedAt': value['finishedAt'] == null ? undefined : ((value['finishedAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'user': UserSimplifiedDtoToJSON(value['user']),
        'roomParticipants': value['roomParticipants'] == null ? undefined : ((value['roomParticipants'] as Array<any>).map(RoomParticipantToJSON)),
    };
}

