/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RoomStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type RoomStatus = typeof RoomStatus[keyof typeof RoomStatus];


export function instanceOfRoomStatus(value: any): boolean {
    for (const key in RoomStatus) {
        if (Object.prototype.hasOwnProperty.call(RoomStatus, key)) {
            if ((RoomStatus as Record<string, RoomStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RoomStatusFromJSON(json: any): RoomStatus {
    return RoomStatusFromJSONTyped(json, false);
}

export function RoomStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomStatus {
    return json as RoomStatus;
}

export function RoomStatusToJSON(value?: RoomStatus | null): any {
    return value as any;
}

