/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemQuestionDto } from './SystemQuestionDto';
import {
    SystemQuestionDtoFromJSON,
    SystemQuestionDtoFromJSONTyped,
    SystemQuestionDtoToJSON,
} from './SystemQuestionDto';

/**
 * 
 * @export
 * @interface SystemQuestionDtoListApiResponse
 */
export interface SystemQuestionDtoListApiResponse {
    /**
     * 
     * @type {number}
     * @memberof SystemQuestionDtoListApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof SystemQuestionDtoListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<SystemQuestionDto>}
     * @memberof SystemQuestionDtoListApiResponse
     */
    data?: Array<SystemQuestionDto> | null;
}

/**
 * Check if a given object implements the SystemQuestionDtoListApiResponse interface.
 */
export function instanceOfSystemQuestionDtoListApiResponse(value: object): value is SystemQuestionDtoListApiResponse {
    return true;
}

export function SystemQuestionDtoListApiResponseFromJSON(json: any): SystemQuestionDtoListApiResponse {
    return SystemQuestionDtoListApiResponseFromJSONTyped(json, false);
}

export function SystemQuestionDtoListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemQuestionDtoListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SystemQuestionDtoFromJSON)),
    };
}

export function SystemQuestionDtoListApiResponseToJSON(value?: SystemQuestionDtoListApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SystemQuestionDtoToJSON)),
    };
}

