/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomStatus } from './RoomStatus';
import {
    RoomStatusFromJSON,
    RoomStatusFromJSONTyped,
    RoomStatusToJSON,
} from './RoomStatus';

/**
 * 
 * @export
 * @interface UpdateRoomDto
 */
export interface UpdateRoomDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateRoomDto
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRoomDto
     */
    description?: string | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateRoomDto
     */
    offers?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateRoomDto
     */
    scheduledAt?: Date | null;
    /**
     * 
     * @type {RoomStatus}
     * @memberof UpdateRoomDto
     */
    status?: RoomStatus;
    /**
     * 
     * @type {Date}
     * @memberof UpdateRoomDto
     */
    finishedAt?: Date | null;
}

/**
 * Check if a given object implements the UpdateRoomDto interface.
 */
export function instanceOfUpdateRoomDto(value: object): value is UpdateRoomDto {
    return true;
}

export function UpdateRoomDtoFromJSON(json: any): UpdateRoomDto {
    return UpdateRoomDtoFromJSONTyped(json, false);
}

export function UpdateRoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'offers': json['offers'] == null ? undefined : json['offers'],
        'scheduledAt': json['scheduledAt'] == null ? undefined : (new Date(json['scheduledAt'])),
        'status': json['status'] == null ? undefined : RoomStatusFromJSON(json['status']),
        'finishedAt': json['finishedAt'] == null ? undefined : (new Date(json['finishedAt'])),
    };
}

export function UpdateRoomDtoToJSON(value?: UpdateRoomDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'offers': value['offers'],
        'scheduledAt': value['scheduledAt'] == null ? undefined : ((value['scheduledAt'] as any).toISOString()),
        'status': RoomStatusToJSON(value['status']),
        'finishedAt': value['finishedAt'] == null ? undefined : ((value['finishedAt'] as any).toISOString()),
    };
}

