/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSystemQuestionDto
 */
export interface UpdateSystemQuestionDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateSystemQuestionDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateSystemQuestionDto
     */
    categoryId?: number;
}

/**
 * Check if a given object implements the UpdateSystemQuestionDto interface.
 */
export function instanceOfUpdateSystemQuestionDto(value: object): value is UpdateSystemQuestionDto {
    return true;
}

export function UpdateSystemQuestionDtoFromJSON(json: any): UpdateSystemQuestionDto {
    return UpdateSystemQuestionDtoFromJSONTyped(json, false);
}

export function UpdateSystemQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSystemQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}

export function UpdateSystemQuestionDtoToJSON(value?: UpdateSystemQuestionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'categoryId': value['categoryId'],
    };
}

