/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Interest } from './Interest';
import {
    InterestFromJSON,
    InterestFromJSONTyped,
    InterestToJSON,
} from './Interest';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * 
 * @export
 * @interface UserProfileInterest
 */
export interface UserProfileInterest {
    /**
     * 
     * @type {number}
     * @memberof UserProfileInterest
     */
    userProfileId?: number;
    /**
     * 
     * @type {number}
     * @memberof UserProfileInterest
     */
    interestId?: number;
    /**
     * 
     * @type {UserProfile}
     * @memberof UserProfileInterest
     */
    userProfile?: UserProfile;
    /**
     * 
     * @type {Interest}
     * @memberof UserProfileInterest
     */
    interest?: Interest;
}

/**
 * Check if a given object implements the UserProfileInterest interface.
 */
export function instanceOfUserProfileInterest(value: object): value is UserProfileInterest {
    return true;
}

export function UserProfileInterestFromJSON(json: any): UserProfileInterest {
    return UserProfileInterestFromJSONTyped(json, false);
}

export function UserProfileInterestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileInterest {
    if (json == null) {
        return json;
    }
    return {
        
        'userProfileId': json['userProfileId'] == null ? undefined : json['userProfileId'],
        'interestId': json['interestId'] == null ? undefined : json['interestId'],
        'userProfile': json['userProfile'] == null ? undefined : UserProfileFromJSON(json['userProfile']),
        'interest': json['interest'] == null ? undefined : InterestFromJSON(json['interest']),
    };
}

export function UserProfileInterestToJSON(value?: UserProfileInterest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userProfileId': value['userProfileId'],
        'interestId': value['interestId'],
        'userProfile': UserProfileToJSON(value['userProfile']),
        'interest': InterestToJSON(value['interest']),
    };
}

