/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRoomDto,
  Room,
  RoomDtoApiResponse,
  UpdateRoomDto,
} from '../models/index';
import {
    CreateRoomDtoFromJSON,
    CreateRoomDtoToJSON,
    RoomFromJSON,
    RoomToJSON,
    RoomDtoApiResponseFromJSON,
    RoomDtoApiResponseToJSON,
    UpdateRoomDtoFromJSON,
    UpdateRoomDtoToJSON,
} from '../models/index';

export interface ApiRoomIdGetRequest {
    id: number;
}

export interface ApiRoomIdPutRequest {
    id: number;
    updateRoomDto?: UpdateRoomDto;
}

export interface ApiRoomPostRequest {
    createRoomDto?: CreateRoomDto;
}

/**
 * 
 */
export class RoomApi extends runtime.BaseAPI {

    /**
     */
    async apiRoomGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Room`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRoomGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRoomGetRaw(initOverrides);
    }

    /**
     */
    async apiRoomIdGetRaw(requestParameters: ApiRoomIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDtoApiResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiRoomIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Room/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRoomIdGet(requestParameters: ApiRoomIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDtoApiResponse> {
        const response = await this.apiRoomIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRoomIdPutRaw(requestParameters: ApiRoomIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiRoomIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Room/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRoomDtoToJSON(requestParameters['updateRoomDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRoomIdPut(requestParameters: ApiRoomIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRoomIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiRoomPostRaw(requestParameters: ApiRoomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Room>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Room`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoomDtoToJSON(requestParameters['createRoomDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomFromJSON(jsonValue));
    }

    /**
     */
    async apiRoomPost(requestParameters: ApiRoomPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Room> {
        const response = await this.apiRoomPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
