/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRoomParticipantDto
 */
export interface CreateRoomParticipantDto {
    /**
     * 
     * @type {number}
     * @memberof CreateRoomParticipantDto
     */
    roomId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRoomParticipantDto
     */
    socketId?: string | null;
}

/**
 * Check if a given object implements the CreateRoomParticipantDto interface.
 */
export function instanceOfCreateRoomParticipantDto(value: object): value is CreateRoomParticipantDto {
    return true;
}

export function CreateRoomParticipantDtoFromJSON(json: any): CreateRoomParticipantDto {
    return CreateRoomParticipantDtoFromJSONTyped(json, false);
}

export function CreateRoomParticipantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRoomParticipantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'roomId': json['roomId'] == null ? undefined : json['roomId'],
        'socketId': json['socketId'] == null ? undefined : json['socketId'],
    };
}

export function CreateRoomParticipantDtoToJSON(value?: CreateRoomParticipantDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'roomId': value['roomId'],
        'socketId': value['socketId'],
    };
}

