/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSystemQuestionDto
 */
export interface CreateSystemQuestionDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSystemQuestionDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateSystemQuestionDto
     */
    categoryId?: number;
}

/**
 * Check if a given object implements the CreateSystemQuestionDto interface.
 */
export function instanceOfCreateSystemQuestionDto(value: object): value is CreateSystemQuestionDto {
    return true;
}

export function CreateSystemQuestionDtoFromJSON(json: any): CreateSystemQuestionDto {
    return CreateSystemQuestionDtoFromJSONTyped(json, false);
}

export function CreateSystemQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSystemQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}

export function CreateSystemQuestionDtoToJSON(value?: CreateSystemQuestionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'categoryId': value['categoryId'],
    };
}

