/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMatchDto,
  Match,
} from '../models/index';
import {
    CreateMatchDtoFromJSON,
    CreateMatchDtoToJSON,
    MatchFromJSON,
    MatchToJSON,
} from '../models/index';

export interface ApiMatchIdGetRequest {
    id: number;
}

export interface ApiMatchPostRequest {
    createMatchDto?: CreateMatchDto;
}

/**
 * 
 */
export class MatchApi extends runtime.BaseAPI {

    /**
     */
    async apiMatchIdGetRaw(requestParameters: ApiMatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMatchIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Match/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMatchIdGet(requestParameters: ApiMatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMatchIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiMatchMyMatchesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Match/myMatches`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMatchMyMatchesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMatchMyMatchesGetRaw(initOverrides);
    }

    /**
     */
    async apiMatchPostRaw(requestParameters: ApiMatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Match>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Match`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMatchDtoToJSON(requestParameters['createMatchDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchFromJSON(jsonValue));
    }

    /**
     */
    async apiMatchPost(requestParameters: ApiMatchPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Match> {
        const response = await this.apiMatchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
