/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  QuestionCategory,
  QuestionCategoryDto,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    QuestionCategoryFromJSON,
    QuestionCategoryToJSON,
    QuestionCategoryDtoFromJSON,
    QuestionCategoryDtoToJSON,
} from '../models/index';

export interface ApiQuestionCategoriesIdDeleteRequest {
    id: number;
}

export interface ApiQuestionCategoriesIdGetRequest {
    id: number;
}

export interface ApiQuestionCategoriesIdPutRequest {
    id: number;
    questionCategoryDto?: QuestionCategoryDto;
}

export interface ApiQuestionCategoriesPostRequest {
    questionCategoryDto?: QuestionCategoryDto;
}

/**
 * 
 */
export class QuestionCategoriesApi extends runtime.BaseAPI {

    /**
     */
    async apiQuestionCategoriesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QuestionCategory>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/QuestionCategories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuestionCategoryFromJSON));
    }

    /**
     */
    async apiQuestionCategoriesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QuestionCategory>> {
        const response = await this.apiQuestionCategoriesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiQuestionCategoriesIdDeleteRaw(requestParameters: ApiQuestionCategoriesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiQuestionCategoriesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/QuestionCategories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiQuestionCategoriesIdDelete(requestParameters: ApiQuestionCategoriesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiQuestionCategoriesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiQuestionCategoriesIdGetRaw(requestParameters: ApiQuestionCategoriesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuestionCategory>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiQuestionCategoriesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/QuestionCategories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionCategoryFromJSON(jsonValue));
    }

    /**
     */
    async apiQuestionCategoriesIdGet(requestParameters: ApiQuestionCategoriesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuestionCategory> {
        const response = await this.apiQuestionCategoriesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiQuestionCategoriesIdPutRaw(requestParameters: ApiQuestionCategoriesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiQuestionCategoriesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/QuestionCategories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: QuestionCategoryDtoToJSON(requestParameters['questionCategoryDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiQuestionCategoriesIdPut(requestParameters: ApiQuestionCategoriesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiQuestionCategoriesIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiQuestionCategoriesPostRaw(requestParameters: ApiQuestionCategoriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuestionCategory>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/QuestionCategories`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuestionCategoryDtoToJSON(requestParameters['questionCategoryDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionCategoryFromJSON(jsonValue));
    }

    /**
     */
    async apiQuestionCategoriesPost(requestParameters: ApiQuestionCategoriesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuestionCategory> {
        const response = await this.apiQuestionCategoriesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
