/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RoomContentDtoListApiResponse,
} from '../models/index';
import {
    RoomContentDtoListApiResponseFromJSON,
    RoomContentDtoListApiResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class RoomContentApi extends runtime.BaseAPI {

    /**
     */
    async apiRoomContentGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomContentDtoListApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/room-content`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomContentDtoListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRoomContentGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomContentDtoListApiResponse> {
        const response = await this.apiRoomContentGetRaw(initOverrides);
        return await response.value();
    }

}
