/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvailableDescriptorDto } from './AvailableDescriptorDto';
import {
    AvailableDescriptorDtoFromJSON,
    AvailableDescriptorDtoFromJSONTyped,
    AvailableDescriptorDtoToJSON,
} from './AvailableDescriptorDto';

/**
 * 
 * @export
 * @interface AvailableDescriptorDtoListApiResponse
 */
export interface AvailableDescriptorDtoListApiResponse {
    /**
     * 
     * @type {number}
     * @memberof AvailableDescriptorDtoListApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof AvailableDescriptorDtoListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<AvailableDescriptorDto>}
     * @memberof AvailableDescriptorDtoListApiResponse
     */
    data?: Array<AvailableDescriptorDto> | null;
}

/**
 * Check if a given object implements the AvailableDescriptorDtoListApiResponse interface.
 */
export function instanceOfAvailableDescriptorDtoListApiResponse(value: object): value is AvailableDescriptorDtoListApiResponse {
    return true;
}

export function AvailableDescriptorDtoListApiResponseFromJSON(json: any): AvailableDescriptorDtoListApiResponse {
    return AvailableDescriptorDtoListApiResponseFromJSONTyped(json, false);
}

export function AvailableDescriptorDtoListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailableDescriptorDtoListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AvailableDescriptorDtoFromJSON)),
    };
}

export function AvailableDescriptorDtoListApiResponseToJSON(value?: AvailableDescriptorDtoListApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AvailableDescriptorDtoToJSON)),
    };
}

