/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockUserDto
 */
export interface BlockUserDto {
    /**
     * 
     * @type {string}
     * @memberof BlockUserDto
     */
    blockedUserId: string;
}

/**
 * Check if a given object implements the BlockUserDto interface.
 */
export function instanceOfBlockUserDto(value: object): value is BlockUserDto {
    if (!('blockedUserId' in value) || value['blockedUserId'] === undefined) return false;
    return true;
}

export function BlockUserDtoFromJSON(json: any): BlockUserDto {
    return BlockUserDtoFromJSONTyped(json, false);
}

export function BlockUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'blockedUserId': json['blockedUserId'],
    };
}

export function BlockUserDtoToJSON(value?: BlockUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'blockedUserId': value['blockedUserId'],
    };
}

