/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ordinates } from './Ordinates';
import {
    OrdinatesFromJSON,
    OrdinatesFromJSONTyped,
    OrdinatesToJSON,
} from './Ordinates';

/**
 * 
 * @export
 * @interface CoordinateSequenceFactory
 */
export interface CoordinateSequenceFactory {
    /**
     * 
     * @type {Ordinates}
     * @memberof CoordinateSequenceFactory
     */
    ordinates?: Ordinates;
}



/**
 * Check if a given object implements the CoordinateSequenceFactory interface.
 */
export function instanceOfCoordinateSequenceFactory(value: object): value is CoordinateSequenceFactory {
    return true;
}

export function CoordinateSequenceFactoryFromJSON(json: any): CoordinateSequenceFactory {
    return CoordinateSequenceFactoryFromJSONTyped(json, false);
}

export function CoordinateSequenceFactoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinateSequenceFactory {
    if (json == null) {
        return json;
    }
    return {
        
        'ordinates': json['ordinates'] == null ? undefined : OrdinatesFromJSON(json['ordinates']),
    };
}

export function CoordinateSequenceFactoryToJSON(value?: CoordinateSequenceFactory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ordinates': OrdinatesToJSON(value['ordinates']),
    };
}

