"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCreateSystemQuestionDto = instanceOfCreateSystemQuestionDto;
exports.CreateSystemQuestionDtoFromJSON = CreateSystemQuestionDtoFromJSON;
exports.CreateSystemQuestionDtoFromJSONTyped = CreateSystemQuestionDtoFromJSONTyped;
exports.CreateSystemQuestionDtoToJSON = CreateSystemQuestionDtoToJSON;
/**
 * Check if a given object implements the CreateSystemQuestionDto interface.
 */
function instanceOfCreateSystemQuestionDto(value) {
    return true;
}
function CreateSystemQuestionDtoFromJSON(json) {
    return CreateSystemQuestionDtoFromJSONTyped(json, false);
}
function CreateSystemQuestionDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'] == null ? undefined : json['name'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}
function CreateSystemQuestionDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'categoryId': value['categoryId'],
    };
}
