"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCreateRoomParticipantDto = instanceOfCreateRoomParticipantDto;
exports.CreateRoomParticipantDtoFromJSON = CreateRoomParticipantDtoFromJSON;
exports.CreateRoomParticipantDtoFromJSONTyped = CreateRoomParticipantDtoFromJSONTyped;
exports.CreateRoomParticipantDtoToJSON = CreateRoomParticipantDtoToJSON;
/**
 * Check if a given object implements the CreateRoomParticipantDto interface.
 */
function instanceOfCreateRoomParticipantDto(value) {
    return true;
}
function CreateRoomParticipantDtoFromJSON(json) {
    return CreateRoomParticipantDtoFromJSONTyped(json, false);
}
function CreateRoomParticipantDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'roomId': json['roomId'] == null ? undefined : json['roomId'],
        'socketId': json['socketId'] == null ? undefined : json['socketId'],
    };
}
function CreateRoomParticipantDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'roomId': value['roomId'],
        'socketId': value['socketId'],
    };
}
