/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserProfileLifeStyleDto } from './UserProfileLifeStyleDto';
import type { Gender } from './Gender';
import type { UserProfileInterestDto } from './UserProfileInterestDto';
/**
 *
 * @export
 * @interface CreateUserProfileDto
 */
export interface CreateUserProfileDto {
    /**
     *
     * @type {Gender}
     * @memberof CreateUserProfileDto
     */
    gender: Gender;
    /**
     *
     * @type {string}
     * @memberof CreateUserProfileDto
     */
    nationality: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserProfileDto
     */
    placeToLive: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserProfileDto
     */
    bio: string;
    /**
     *
     * @type {number}
     * @memberof CreateUserProfileDto
     */
    height: number;
    /**
     *
     * @type {string}
     * @memberof CreateUserProfileDto
     */
    relationshipGoal: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserProfileDto
     */
    education: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserProfileDto
     */
    zodiac: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserProfileDto
     */
    loveStyle: string;
    /**
     *
     * @type {Array<UserProfileInterestDto>}
     * @memberof CreateUserProfileDto
     */
    userProfileInterests?: Array<UserProfileInterestDto> | null;
    /**
     *
     * @type {Array<UserProfileLifeStyleDto>}
     * @memberof CreateUserProfileDto
     */
    userProfileLifeStyles?: Array<UserProfileLifeStyleDto> | null;
}
/**
 * Check if a given object implements the CreateUserProfileDto interface.
 */
export declare function instanceOfCreateUserProfileDto(value: object): value is CreateUserProfileDto;
export declare function CreateUserProfileDtoFromJSON(json: any): CreateUserProfileDto;
export declare function CreateUserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserProfileDto;
export declare function CreateUserProfileDtoToJSON(value?: CreateUserProfileDto | null): any;
