/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SelectedDescriptor } from './SelectedDescriptor';
import {
    SelectedDescriptorFromJSON,
    SelectedDescriptorFromJSONTyped,
    SelectedDescriptorToJSON,
} from './SelectedDescriptor';
import type { UserProfileGenderDto } from './UserProfileGenderDto';
import {
    UserProfileGenderDtoFromJSON,
    UserProfileGenderDtoFromJSONTyped,
    UserProfileGenderDtoToJSON,
} from './UserProfileGenderDto';

/**
 * 
 * @export
 * @interface CreateOrUpdateUserProfileDto
 */
export interface CreateOrUpdateUserProfileDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateUserProfileDto
     */
    placeToLive?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateUserProfileDto
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateUserProfileDto
     */
    loveStyle?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateOrUpdateUserProfileDto
     */
    ageFilterMax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateOrUpdateUserProfileDto
     */
    ageFilterMin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateOrUpdateUserProfileDto
     */
    distanceFilter?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateUserProfileDto
     */
    pos?: string | null;
    /**
     * 
     * @type {any}
     * @memberof CreateOrUpdateUserProfileDto
     */
    location?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateUserProfileDto
     */
    job?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateUserProfileDto
     */
    school?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateOrUpdateUserProfileDto
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateUserProfileDto
     */
    userId?: string | null;
    /**
     * 
     * @type {Array<SelectedDescriptor>}
     * @memberof CreateOrUpdateUserProfileDto
     */
    selectedDescriptors?: Array<SelectedDescriptor> | null;
    /**
     * 
     * @type {Array<UserProfileGenderDto>}
     * @memberof CreateOrUpdateUserProfileDto
     */
    userProfileGenders?: Array<UserProfileGenderDto> | null;
}

/**
 * Check if a given object implements the CreateOrUpdateUserProfileDto interface.
 */
export function instanceOfCreateOrUpdateUserProfileDto(value: object): value is CreateOrUpdateUserProfileDto {
    return true;
}

export function CreateOrUpdateUserProfileDtoFromJSON(json: any): CreateOrUpdateUserProfileDto {
    return CreateOrUpdateUserProfileDtoFromJSONTyped(json, false);
}

export function CreateOrUpdateUserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrUpdateUserProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'placeToLive': json['placeToLive'] == null ? undefined : json['placeToLive'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'loveStyle': json['loveStyle'] == null ? undefined : json['loveStyle'],
        'ageFilterMax': json['ageFilterMax'] == null ? undefined : json['ageFilterMax'],
        'ageFilterMin': json['ageFilterMin'] == null ? undefined : json['ageFilterMin'],
        'distanceFilter': json['distanceFilter'] == null ? undefined : json['distanceFilter'],
        'pos': json['pos'] == null ? undefined : json['pos'],
        'location': json['location'] == null ? undefined : json['location'],
        'job': json['job'] == null ? undefined : json['job'],
        'school': json['school'] == null ? undefined : json['school'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'selectedDescriptors': json['selectedDescriptors'] == null ? undefined : ((json['selectedDescriptors'] as Array<any>).map(SelectedDescriptorFromJSON)),
        'userProfileGenders': json['userProfileGenders'] == null ? undefined : ((json['userProfileGenders'] as Array<any>).map(UserProfileGenderDtoFromJSON)),
    };
}

export function CreateOrUpdateUserProfileDtoToJSON(value?: CreateOrUpdateUserProfileDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'placeToLive': value['placeToLive'],
        'bio': value['bio'],
        'loveStyle': value['loveStyle'],
        'ageFilterMax': value['ageFilterMax'],
        'ageFilterMin': value['ageFilterMin'],
        'distanceFilter': value['distanceFilter'],
        'pos': value['pos'],
        'location': value['location'],
        'job': value['job'],
        'school': value['school'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate'] as any).toISOString()),
        'userId': value['userId'],
        'selectedDescriptors': value['selectedDescriptors'] == null ? undefined : ((value['selectedDescriptors'] as Array<any>).map(SelectedDescriptorToJSON)),
        'userProfileGenders': value['userProfileGenders'] == null ? undefined : ((value['userProfileGenders'] as Array<any>).map(UserProfileGenderDtoToJSON)),
    };
}

