/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Dimension = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_MINUS_3: -3,
    NUMBER_MINUS_2: -2,
    NUMBER_MINUS_1: -1
} as const;
export type Dimension = typeof Dimension[keyof typeof Dimension];


export function instanceOfDimension(value: any): boolean {
    for (const key in Dimension) {
        if (Object.prototype.hasOwnProperty.call(Dimension, key)) {
            if (Dimension[key as keyof typeof Dimension] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DimensionFromJSON(json: any): Dimension {
    return DimensionFromJSONTyped(json, false);
}

export function DimensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dimension {
    return json as Dimension;
}

export function DimensionToJSON(value?: Dimension | null): any {
    return value as any;
}

