/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinateSequenceFactory } from './CoordinateSequenceFactory';
import {
    CoordinateSequenceFactoryFromJSON,
    CoordinateSequenceFactoryFromJSONTyped,
    CoordinateSequenceFactoryToJSON,
} from './CoordinateSequenceFactory';
import type { PrecisionModel } from './PrecisionModel';
import {
    PrecisionModelFromJSON,
    PrecisionModelFromJSONTyped,
    PrecisionModelToJSON,
} from './PrecisionModel';
import type { NtsGeometryServices } from './NtsGeometryServices';
import {
    NtsGeometryServicesFromJSON,
    NtsGeometryServicesFromJSONTyped,
    NtsGeometryServicesToJSON,
} from './NtsGeometryServices';

/**
 * 
 * @export
 * @interface GeometryFactory
 */
export interface GeometryFactory {
    /**
     * 
     * @type {PrecisionModel}
     * @memberof GeometryFactory
     */
    precisionModel?: PrecisionModel;
    /**
     * 
     * @type {CoordinateSequenceFactory}
     * @memberof GeometryFactory
     */
    coordinateSequenceFactory?: CoordinateSequenceFactory;
    /**
     * 
     * @type {number}
     * @memberof GeometryFactory
     */
    readonly srid?: number;
    /**
     * 
     * @type {NtsGeometryServices}
     * @memberof GeometryFactory
     */
    geometryServices?: NtsGeometryServices;
}

/**
 * Check if a given object implements the GeometryFactory interface.
 */
export function instanceOfGeometryFactory(value: object): value is GeometryFactory {
    return true;
}

export function GeometryFactoryFromJSON(json: any): GeometryFactory {
    return GeometryFactoryFromJSONTyped(json, false);
}

export function GeometryFactoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeometryFactory {
    if (json == null) {
        return json;
    }
    return {
        
        'precisionModel': json['precisionModel'] == null ? undefined : PrecisionModelFromJSON(json['precisionModel']),
        'coordinateSequenceFactory': json['coordinateSequenceFactory'] == null ? undefined : CoordinateSequenceFactoryFromJSON(json['coordinateSequenceFactory']),
        'srid': json['srid'] == null ? undefined : json['srid'],
        'geometryServices': json['geometryServices'] == null ? undefined : NtsGeometryServicesFromJSON(json['geometryServices']),
    };
}

export function GeometryFactoryToJSON(value?: Omit<GeometryFactory, 'srid'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'precisionModel': PrecisionModelToJSON(value['precisionModel']),
        'coordinateSequenceFactory': CoordinateSequenceFactoryToJSON(value['coordinateSequenceFactory']),
        'geometryServices': NtsGeometryServicesToJSON(value['geometryServices']),
    };
}

