/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeometryFactory } from './GeometryFactory';
import {
    GeometryFactoryFromJSON,
    GeometryFactoryFromJSONTyped,
    GeometryFactoryToJSON,
} from './GeometryFactory';
import type { Coordinate } from './Coordinate';
import {
    CoordinateFromJSON,
    CoordinateFromJSONTyped,
    CoordinateToJSON,
} from './Coordinate';
import type { PrecisionModel } from './PrecisionModel';
import {
    PrecisionModelFromJSON,
    PrecisionModelFromJSONTyped,
    PrecisionModelToJSON,
} from './PrecisionModel';
import type { Dimension } from './Dimension';
import {
    DimensionFromJSON,
    DimensionFromJSONTyped,
    DimensionToJSON,
} from './Dimension';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './Point';
import type { Envelope } from './Envelope';
import {
    EnvelopeFromJSON,
    EnvelopeFromJSONTyped,
    EnvelopeToJSON,
} from './Envelope';
import type { OgcGeometryType } from './OgcGeometryType';
import {
    OgcGeometryTypeFromJSON,
    OgcGeometryTypeFromJSONTyped,
    OgcGeometryTypeToJSON,
} from './OgcGeometryType';

/**
 * 
 * @export
 * @interface Geometry
 */
export interface Geometry {
    /**
     * 
     * @type {GeometryFactory}
     * @memberof Geometry
     */
    factory?: GeometryFactory;
    /**
     * 
     * @type {any}
     * @memberof Geometry
     */
    userData?: any | null;
    /**
     * 
     * @type {number}
     * @memberof Geometry
     */
    srid?: number;
    /**
     * 
     * @type {string}
     * @memberof Geometry
     */
    readonly geometryType?: string | null;
    /**
     * 
     * @type {OgcGeometryType}
     * @memberof Geometry
     */
    ogcGeometryType?: OgcGeometryType;
    /**
     * 
     * @type {PrecisionModel}
     * @memberof Geometry
     */
    precisionModel?: PrecisionModel;
    /**
     * 
     * @type {Coordinate}
     * @memberof Geometry
     */
    coordinate?: Coordinate;
    /**
     * 
     * @type {Array<Coordinate>}
     * @memberof Geometry
     */
    readonly coordinates?: Array<Coordinate> | null;
    /**
     * 
     * @type {number}
     * @memberof Geometry
     */
    readonly numPoints?: number;
    /**
     * 
     * @type {number}
     * @memberof Geometry
     */
    readonly numGeometries?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Geometry
     */
    readonly isSimple?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Geometry
     */
    readonly isValid?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Geometry
     */
    readonly isEmpty?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Geometry
     */
    readonly area?: number;
    /**
     * 
     * @type {number}
     * @memberof Geometry
     */
    readonly length?: number;
    /**
     * 
     * @type {Point}
     * @memberof Geometry
     */
    centroid?: Point;
    /**
     * 
     * @type {Point}
     * @memberof Geometry
     */
    interiorPoint?: Point;
    /**
     * 
     * @type {Point}
     * @memberof Geometry
     */
    pointOnSurface?: Point;
    /**
     * 
     * @type {Dimension}
     * @memberof Geometry
     */
    dimension?: Dimension;
    /**
     * 
     * @type {Geometry}
     * @memberof Geometry
     */
    boundary?: Geometry;
    /**
     * 
     * @type {Dimension}
     * @memberof Geometry
     */
    boundaryDimension?: Dimension;
    /**
     * 
     * @type {Geometry}
     * @memberof Geometry
     */
    envelope?: Geometry;
    /**
     * 
     * @type {Envelope}
     * @memberof Geometry
     */
    envelopeInternal?: Envelope;
    /**
     * 
     * @type {boolean}
     * @memberof Geometry
     */
    readonly isRectangle?: boolean;
}



/**
 * Check if a given object implements the Geometry interface.
 */
export function instanceOfGeometry(value: object): value is Geometry {
    return true;
}

export function GeometryFromJSON(json: any): Geometry {
    return GeometryFromJSONTyped(json, false);
}

export function GeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Geometry {
    if (json == null) {
        return json;
    }
    return {
        
        'factory': json['factory'] == null ? undefined : GeometryFactoryFromJSON(json['factory']),
        'userData': json['userData'] == null ? undefined : json['userData'],
        'srid': json['srid'] == null ? undefined : json['srid'],
        'geometryType': json['geometryType'] == null ? undefined : json['geometryType'],
        'ogcGeometryType': json['ogcGeometryType'] == null ? undefined : OgcGeometryTypeFromJSON(json['ogcGeometryType']),
        'precisionModel': json['precisionModel'] == null ? undefined : PrecisionModelFromJSON(json['precisionModel']),
        'coordinate': json['coordinate'] == null ? undefined : CoordinateFromJSON(json['coordinate']),
        'coordinates': json['coordinates'] == null ? undefined : ((json['coordinates'] as Array<any>).map(CoordinateFromJSON)),
        'numPoints': json['numPoints'] == null ? undefined : json['numPoints'],
        'numGeometries': json['numGeometries'] == null ? undefined : json['numGeometries'],
        'isSimple': json['isSimple'] == null ? undefined : json['isSimple'],
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'isEmpty': json['isEmpty'] == null ? undefined : json['isEmpty'],
        'area': json['area'] == null ? undefined : json['area'],
        'length': json['length'] == null ? undefined : json['length'],
        'centroid': json['centroid'] == null ? undefined : PointFromJSON(json['centroid']),
        'interiorPoint': json['interiorPoint'] == null ? undefined : PointFromJSON(json['interiorPoint']),
        'pointOnSurface': json['pointOnSurface'] == null ? undefined : PointFromJSON(json['pointOnSurface']),
        'dimension': json['dimension'] == null ? undefined : DimensionFromJSON(json['dimension']),
        'boundary': json['boundary'] == null ? undefined : GeometryFromJSON(json['boundary']),
        'boundaryDimension': json['boundaryDimension'] == null ? undefined : DimensionFromJSON(json['boundaryDimension']),
        'envelope': json['envelope'] == null ? undefined : GeometryFromJSON(json['envelope']),
        'envelopeInternal': json['envelopeInternal'] == null ? undefined : EnvelopeFromJSON(json['envelopeInternal']),
        'isRectangle': json['isRectangle'] == null ? undefined : json['isRectangle'],
    };
}

export function GeometryToJSON(value?: Omit<Geometry, 'geometryType'|'coordinates'|'numPoints'|'numGeometries'|'isSimple'|'isValid'|'isEmpty'|'area'|'length'|'isRectangle'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'factory': GeometryFactoryToJSON(value['factory']),
        'userData': value['userData'],
        'srid': value['srid'],
        'ogcGeometryType': OgcGeometryTypeToJSON(value['ogcGeometryType']),
        'precisionModel': PrecisionModelToJSON(value['precisionModel']),
        'coordinate': CoordinateToJSON(value['coordinate']),
        'centroid': PointToJSON(value['centroid']),
        'interiorPoint': PointToJSON(value['interiorPoint']),
        'pointOnSurface': PointToJSON(value['pointOnSurface']),
        'dimension': DimensionToJSON(value['dimension']),
        'boundary': GeometryToJSON(value['boundary']),
        'boundaryDimension': DimensionToJSON(value['boundaryDimension']),
        'envelope': GeometryToJSON(value['envelope']),
        'envelopeInternal': EnvelopeToJSON(value['envelopeInternal']),
    };
}

