/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserProfileInterest } from './UserProfileInterest';
/**
 *
 * @export
 * @interface Interest
 */
export interface Interest {
    /**
     *
     * @type {number}
     * @memberof Interest
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof Interest
     */
    name?: string | null;
    /**
     *
     * @type {Date}
     * @memberof Interest
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof Interest
     */
    updatedAt?: Date;
    /**
     *
     * @type {Array<UserProfileInterest>}
     * @memberof Interest
     */
    userProfileInterests?: Array<UserProfileInterest> | null;
}
/**
 * Check if a given object implements the Interest interface.
 */
export declare function instanceOfInterest(value: object): value is Interest;
export declare function InterestFromJSON(json: any): Interest;
export declare function InterestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Interest;
export declare function InterestToJSON(value?: Interest | null): any;
