/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileLifeStyle } from './UserProfileLifeStyle';
import {
    UserProfileLifeStyleFromJSON,
    UserProfileLifeStyleFromJSONTyped,
    UserProfileLifeStyleToJSON,
} from './UserProfileLifeStyle';

/**
 * 
 * @export
 * @interface LifeStyle
 */
export interface LifeStyle {
    /**
     * 
     * @type {number}
     * @memberof LifeStyle
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LifeStyle
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LifeStyle
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof LifeStyle
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<UserProfileLifeStyle>}
     * @memberof LifeStyle
     */
    userProfileLifeStyles?: Array<UserProfileLifeStyle> | null;
}

/**
 * Check if a given object implements the LifeStyle interface.
 */
export function instanceOfLifeStyle(value: object): value is LifeStyle {
    return true;
}

export function LifeStyleFromJSON(json: any): LifeStyle {
    return LifeStyleFromJSONTyped(json, false);
}

export function LifeStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): LifeStyle {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userProfileLifeStyles': json['userProfileLifeStyles'] == null ? undefined : ((json['userProfileLifeStyles'] as Array<any>).map(UserProfileLifeStyleFromJSON)),
    };
}

export function LifeStyleToJSON(value?: LifeStyle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'userProfileLifeStyles': value['userProfileLifeStyles'] == null ? undefined : ((value['userProfileLifeStyles'] as Array<any>).map(UserProfileLifeStyleToJSON)),
    };
}

