/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserProfileLifeStyle } from './UserProfileLifeStyle';
/**
 *
 * @export
 * @interface LifeStyle
 */
export interface LifeStyle {
    /**
     *
     * @type {number}
     * @memberof LifeStyle
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof LifeStyle
     */
    name?: string | null;
    /**
     *
     * @type {Date}
     * @memberof LifeStyle
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof LifeStyle
     */
    updatedAt?: Date;
    /**
     *
     * @type {Array<UserProfileLifeStyle>}
     * @memberof LifeStyle
     */
    userProfileLifeStyles?: Array<UserProfileLifeStyle> | null;
}
/**
 * Check if a given object implements the LifeStyle interface.
 */
export declare function instanceOfLifeStyle(value: object): value is LifeStyle;
export declare function LifeStyleFromJSON(json: any): LifeStyle;
export declare function LifeStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): LifeStyle;
export declare function LifeStyleToJSON(value?: LifeStyle | null): any;
