/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     *
     * @type {string}
     * @memberof LoginDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof LoginDto
     */
    password: string;
}
/**
 * Check if a given object implements the LoginDto interface.
 */
export declare function instanceOfLoginDto(value: object): value is LoginDto;
export declare function LoginDtoFromJSON(json: any): LoginDto;
export declare function LoginDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginDto;
export declare function LoginDtoToJSON(value?: LoginDto | null): any;
