"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfMatch = instanceOfMatch;
exports.MatchFromJSON = MatchFromJSON;
exports.MatchFromJSONTyped = MatchFromJSONTyped;
exports.MatchToJSON = MatchToJSON;
var User_1 = require("./User");
var MatchOrigin_1 = require("./MatchOrigin");
/**
 * Check if a given object implements the Match interface.
 */
function instanceOfMatch(value) {
    return true;
}
function MatchFromJSON(json) {
    return MatchFromJSONTyped(json, false);
}
function MatchFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'user1Id': json['user1Id'] == null ? undefined : json['user1Id'],
        'user1': json['user1'] == null ? undefined : (0, User_1.UserFromJSON)(json['user1']),
        'user2Id': json['user2Id'] == null ? undefined : json['user2Id'],
        'user2': json['user2'] == null ? undefined : (0, User_1.UserFromJSON)(json['user2']),
        'origin': json['origin'] == null ? undefined : (0, MatchOrigin_1.MatchOriginFromJSON)(json['origin']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}
function MatchToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'user1Id': value['user1Id'],
        'user1': (0, User_1.UserToJSON)(value['user1']),
        'user2Id': value['user2Id'],
        'user2': (0, User_1.UserToJSON)(value['user2']),
        'origin': (0, MatchOrigin_1.MatchOriginToJSON)(value['origin']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}
