/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const MatchOrigin: {
    readonly NUMBER_0: 0;
    readonly NUMBER_1: 1;
};
export type MatchOrigin = typeof MatchOrigin[keyof typeof MatchOrigin];
export declare function instanceOfMatchOrigin(value: any): boolean;
export declare function MatchOriginFromJSON(json: any): MatchOrigin;
export declare function MatchOriginFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchOrigin;
export declare function MatchOriginToJSON(value?: MatchOrigin | null): any;
