"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MatchOrigin = void 0;
exports.instanceOfMatchOrigin = instanceOfMatchOrigin;
exports.MatchOriginFromJSON = MatchOriginFromJSON;
exports.MatchOriginFromJSONTyped = MatchOriginFromJSONTyped;
exports.MatchOriginToJSON = MatchOriginToJSON;
/**
 *
 * @export
 */
exports.MatchOrigin = {
    NUMBER_0: 0,
    NUMBER_1: 1
};
function instanceOfMatchOrigin(value) {
    for (var key in exports.MatchOrigin) {
        if (Object.prototype.hasOwnProperty.call(exports.MatchOrigin, key)) {
            if (exports.MatchOrigin[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function MatchOriginFromJSON(json) {
    return MatchOriginFromJSONTyped(json, false);
}
function MatchOriginFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function MatchOriginToJSON(value) {
    return value;
}
