/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { User } from './User';
import type { MediaType } from './MediaType';
/**
 *
 * @export
 * @interface Media
 */
export interface Media {
    /**
     *
     * @type {number}
     * @memberof Media
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof Media
     */
    url: string;
    /**
     *
     * @type {Date}
     * @memberof Media
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof Media
     */
    updatedAt?: Date;
    /**
     *
     * @type {MediaType}
     * @memberof Media
     */
    mediaType: MediaType;
    /**
     *
     * @type {string}
     * @memberof Media
     */
    userId?: string | null;
    /**
     *
     * @type {User}
     * @memberof Media
     */
    user?: User;
}
/**
 * Check if a given object implements the Media interface.
 */
export declare function instanceOfMedia(value: object): value is Media;
export declare function MediaFromJSON(json: any): Media;
export declare function MediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Media;
export declare function MediaToJSON(value?: Media | null): any;
