/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MyRoomStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type MyRoomStatus = typeof MyRoomStatus[keyof typeof MyRoomStatus];


export function instanceOfMyRoomStatus(value: any): boolean {
    for (const key in MyRoomStatus) {
        if (Object.prototype.hasOwnProperty.call(MyRoomStatus, key)) {
            if (MyRoomStatus[key as keyof typeof MyRoomStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MyRoomStatusFromJSON(json: any): MyRoomStatus {
    return MyRoomStatusFromJSONTyped(json, false);
}

export function MyRoomStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyRoomStatus {
    return json as MyRoomStatus;
}

export function MyRoomStatusToJSON(value?: MyRoomStatus | null): any {
    return value as any;
}

