/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PrecisionModels = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type PrecisionModels = typeof PrecisionModels[keyof typeof PrecisionModels];


export function instanceOfPrecisionModels(value: any): boolean {
    for (const key in PrecisionModels) {
        if (Object.prototype.hasOwnProperty.call(PrecisionModels, key)) {
            if (PrecisionModels[key as keyof typeof PrecisionModels] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PrecisionModelsFromJSON(json: any): PrecisionModels {
    return PrecisionModelsFromJSONTyped(json, false);
}

export function PrecisionModelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrecisionModels {
    return json as PrecisionModels;
}

export function PrecisionModelsToJSON(value?: PrecisionModels | null): any {
    return value as any;
}

