/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrecisionModels } from './PrecisionModels';
import {
    PrecisionModelsFromJSON,
    PrecisionModelsFromJSONTyped,
    PrecisionModelsToJSON,
} from './PrecisionModels';

/**
 * 
 * @export
 * @interface PrecisionModel
 */
export interface PrecisionModel {
    /**
     * 
     * @type {boolean}
     * @memberof PrecisionModel
     */
    readonly isFloating?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PrecisionModel
     */
    readonly maximumSignificantDigits?: number;
    /**
     * 
     * @type {number}
     * @memberof PrecisionModel
     */
    scale?: number;
    /**
     * 
     * @type {number}
     * @memberof PrecisionModel
     */
    readonly gridSize?: number;
    /**
     * 
     * @type {PrecisionModels}
     * @memberof PrecisionModel
     */
    precisionModelType?: PrecisionModels;
}



/**
 * Check if a given object implements the PrecisionModel interface.
 */
export function instanceOfPrecisionModel(value: object): value is PrecisionModel {
    return true;
}

export function PrecisionModelFromJSON(json: any): PrecisionModel {
    return PrecisionModelFromJSONTyped(json, false);
}

export function PrecisionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrecisionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'isFloating': json['isFloating'] == null ? undefined : json['isFloating'],
        'maximumSignificantDigits': json['maximumSignificantDigits'] == null ? undefined : json['maximumSignificantDigits'],
        'scale': json['scale'] == null ? undefined : json['scale'],
        'gridSize': json['gridSize'] == null ? undefined : json['gridSize'],
        'precisionModelType': json['precisionModelType'] == null ? undefined : PrecisionModelsFromJSON(json['precisionModelType']),
    };
}

export function PrecisionModelToJSON(value?: Omit<PrecisionModel, 'isFloating'|'maximumSignificantDigits'|'gridSize'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'scale': value['scale'],
        'precisionModelType': PrecisionModelsToJSON(value['precisionModelType']),
    };
}

