/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    [key: string]: any | any;
    /**
     *
     * @type {string}
     * @memberof ProblemDetails
     */
    type?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProblemDetails
     */
    title?: string | null;
    /**
     *
     * @type {number}
     * @memberof ProblemDetails
     */
    status?: number | null;
    /**
     *
     * @type {string}
     * @memberof ProblemDetails
     */
    detail?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProblemDetails
     */
    instance?: string | null;
}
/**
 * Check if a given object implements the ProblemDetails interface.
 */
export declare function instanceOfProblemDetails(value: object): value is ProblemDetails;
export declare function ProblemDetailsFromJSON(json: any): ProblemDetails;
export declare function ProblemDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetails;
export declare function ProblemDetailsToJSON(value?: ProblemDetails | null): any;
