/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SystemQuestion } from './SystemQuestion';
/**
 *
 * @export
 * @interface QuestionCategory
 */
export interface QuestionCategory {
    /**
     *
     * @type {number}
     * @memberof QuestionCategory
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof QuestionCategory
     */
    name?: string | null;
    /**
     *
     * @type {Date}
     * @memberof QuestionCategory
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof QuestionCategory
     */
    updatedAt?: Date;
    /**
     *
     * @type {Array<SystemQuestion>}
     * @memberof QuestionCategory
     */
    systemQuestions?: Array<SystemQuestion> | null;
}
/**
 * Check if a given object implements the QuestionCategory interface.
 */
export declare function instanceOfQuestionCategory(value: object): value is QuestionCategory;
export declare function QuestionCategoryFromJSON(json: any): QuestionCategory;
export declare function QuestionCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionCategory;
export declare function QuestionCategoryToJSON(value?: QuestionCategory | null): any;
