/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemQuestion } from './SystemQuestion';
import {
    SystemQuestionFromJSON,
    SystemQuestionFromJSONTyped,
    SystemQuestionToJSON,
} from './SystemQuestion';

/**
 * 
 * @export
 * @interface QuestionCategory
 */
export interface QuestionCategory {
    /**
     * 
     * @type {number}
     * @memberof QuestionCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof QuestionCategory
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof QuestionCategory
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof QuestionCategory
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<SystemQuestion>}
     * @memberof QuestionCategory
     */
    systemQuestions?: Array<SystemQuestion> | null;
}

/**
 * Check if a given object implements the QuestionCategory interface.
 */
export function instanceOfQuestionCategory(value: object): value is QuestionCategory {
    return true;
}

export function QuestionCategoryFromJSON(json: any): QuestionCategory {
    return QuestionCategoryFromJSONTyped(json, false);
}

export function QuestionCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'systemQuestions': json['systemQuestions'] == null ? undefined : ((json['systemQuestions'] as Array<any>).map(SystemQuestionFromJSON)),
    };
}

export function QuestionCategoryToJSON(value?: QuestionCategory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'systemQuestions': value['systemQuestions'] == null ? undefined : ((value['systemQuestions'] as Array<any>).map(SystemQuestionToJSON)),
    };
}

