/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionCategoryDto
 */
export interface QuestionCategoryDto {
    /**
     * 
     * @type {number}
     * @memberof QuestionCategoryDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof QuestionCategoryDto
     */
    name?: string | null;
}

/**
 * Check if a given object implements the QuestionCategoryDto interface.
 */
export function instanceOfQuestionCategoryDto(value: object): value is QuestionCategoryDto {
    return true;
}

export function QuestionCategoryDtoFromJSON(json: any): QuestionCategoryDto {
    return QuestionCategoryDtoFromJSONTyped(json, false);
}

export function QuestionCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function QuestionCategoryDtoToJSON(value?: QuestionCategoryDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

