/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { QuestionCategoryDto } from './QuestionCategoryDto';
/**
 *
 * @export
 * @interface QuestionCategoryDtoListApiResponse
 */
export interface QuestionCategoryDtoListApiResponse {
    /**
     *
     * @type {number}
     * @memberof QuestionCategoryDtoListApiResponse
     */
    statusCode?: number;
    /**
     *
     * @type {string}
     * @memberof QuestionCategoryDtoListApiResponse
     */
    message?: string | null;
    /**
     *
     * @type {Array<QuestionCategoryDto>}
     * @memberof QuestionCategoryDtoListApiResponse
     */
    data?: Array<QuestionCategoryDto> | null;
}
/**
 * Check if a given object implements the QuestionCategoryDtoListApiResponse interface.
 */
export declare function instanceOfQuestionCategoryDtoListApiResponse(value: object): value is QuestionCategoryDtoListApiResponse;
export declare function QuestionCategoryDtoListApiResponseFromJSON(json: any): QuestionCategoryDtoListApiResponse;
export declare function QuestionCategoryDtoListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionCategoryDtoListApiResponse;
export declare function QuestionCategoryDtoListApiResponseToJSON(value?: QuestionCategoryDtoListApiResponse | null): any;
