"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRoomDtoPagedResponse = instanceOfRoomDtoPagedResponse;
exports.RoomDtoPagedResponseFromJSON = RoomDtoPagedResponseFromJSON;
exports.RoomDtoPagedResponseFromJSONTyped = RoomDtoPagedResponseFromJSONTyped;
exports.RoomDtoPagedResponseToJSON = RoomDtoPagedResponseToJSON;
var RoomDto_1 = require("./RoomDto");
/**
 * Check if a given object implements the RoomDtoPagedResponse interface.
 */
function instanceOfRoomDtoPagedResponse(value) {
    return true;
}
function RoomDtoPagedResponseFromJSON(json) {
    return RoomDtoPagedResponseFromJSONTyped(json, false);
}
function RoomDtoPagedResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'data': json['data'] == null ? undefined : (json['data'].map(RoomDto_1.RoomDtoFromJSON)),
    };
}
function RoomDtoPagedResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'currentPage': value['currentPage'],
        'pageSize': value['pageSize'],
        'data': value['data'] == null ? undefined : (value['data'].map(RoomDto_1.RoomDtoToJSON)),
    };
}
