/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomDto } from './RoomDto';
import {
    RoomDtoFromJSON,
    RoomDtoFromJSONTyped,
    RoomDtoToJSON,
} from './RoomDto';

/**
 * 
 * @export
 * @interface RoomDtoApiResponse
 */
export interface RoomDtoApiResponse {
    /**
     * 
     * @type {number}
     * @memberof RoomDtoApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof RoomDtoApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {RoomDto}
     * @memberof RoomDtoApiResponse
     */
    data?: RoomDto;
}

/**
 * Check if a given object implements the RoomDtoApiResponse interface.
 */
export function instanceOfRoomDtoApiResponse(value: object): value is RoomDtoApiResponse {
    return true;
}

export function RoomDtoApiResponseFromJSON(json: any): RoomDtoApiResponse {
    return RoomDtoApiResponseFromJSONTyped(json, false);
}

export function RoomDtoApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomDtoApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : RoomDtoFromJSON(json['data']),
    };
}

export function RoomDtoApiResponseToJSON(value?: RoomDtoApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': RoomDtoToJSON(value['data']),
    };
}

