/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { User } from './User';
import type { Room } from './Room';
/**
 *
 * @export
 * @interface RoomParticipant
 */
export interface RoomParticipant {
    /**
     *
     * @type {number}
     * @memberof RoomParticipant
     */
    roomId?: number;
    /**
     *
     * @type {string}
     * @memberof RoomParticipant
     */
    userId?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof RoomParticipant
     */
    isInterested?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RoomParticipant
     */
    attended?: boolean;
    /**
     *
     * @type {Date}
     * @memberof RoomParticipant
     */
    attendedFromTime?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof RoomParticipant
     */
    attendedToTime?: Date | null;
    /**
     *
     * @type {string}
     * @memberof RoomParticipant
     */
    socketId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof RoomParticipant
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof RoomParticipant
     */
    updatedAt?: Date;
    /**
     *
     * @type {Room}
     * @memberof RoomParticipant
     */
    room?: Room;
    /**
     *
     * @type {User}
     * @memberof RoomParticipant
     */
    user?: User;
}
/**
 * Check if a given object implements the RoomParticipant interface.
 */
export declare function instanceOfRoomParticipant(value: object): value is RoomParticipant;
export declare function RoomParticipantFromJSON(json: any): RoomParticipant;
export declare function RoomParticipantFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomParticipant;
export declare function RoomParticipantToJSON(value?: RoomParticipant | null): any;
