"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRoomContentDto = instanceOfRoomContentDto;
exports.RoomContentDtoFromJSON = RoomContentDtoFromJSON;
exports.RoomContentDtoFromJSONTyped = RoomContentDtoFromJSONTyped;
exports.RoomContentDtoToJSON = RoomContentDtoToJSON;
/**
 * Check if a given object implements the RoomContentDto interface.
 */
function instanceOfRoomContentDto(value) {
    return true;
}
function RoomContentDtoFromJSON(json) {
    return RoomContentDtoFromJSONTyped(json, false);
}
function RoomContentDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}
function RoomContentDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'order': value['order'],
        'duration': value['duration'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}
