/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomContentDto
 */
export interface RoomContentDto {
    /**
     * 
     * @type {number}
     * @memberof RoomContentDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoomContentDto
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoomContentDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RoomContentDto
     */
    order?: number;
    /**
     * 
     * @type {number}
     * @memberof RoomContentDto
     */
    duration?: number;
    /**
     * 
     * @type {Date}
     * @memberof RoomContentDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RoomContentDto
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the RoomContentDto interface.
 */
export function instanceOfRoomContentDto(value: object): value is RoomContentDto {
    return true;
}

export function RoomContentDtoFromJSON(json: any): RoomContentDto {
    return RoomContentDtoFromJSONTyped(json, false);
}

export function RoomContentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomContentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function RoomContentDtoToJSON(value?: RoomContentDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'order': value['order'],
        'duration': value['duration'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

