/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { RoomDto } from './RoomDto';
/**
 *
 * @export
 * @interface RoomDtoPagedResponse
 */
export interface RoomDtoPagedResponse {
    /**
     *
     * @type {number}
     * @memberof RoomDtoPagedResponse
     */
    totalItems?: number;
    /**
     *
     * @type {number}
     * @memberof RoomDtoPagedResponse
     */
    totalPages?: number;
    /**
     *
     * @type {number}
     * @memberof RoomDtoPagedResponse
     */
    currentPage?: number;
    /**
     *
     * @type {number}
     * @memberof RoomDtoPagedResponse
     */
    pageSize?: number;
    /**
     *
     * @type {Array<RoomDto>}
     * @memberof RoomDtoPagedResponse
     */
    data?: Array<RoomDto> | null;
}
/**
 * Check if a given object implements the RoomDtoPagedResponse interface.
 */
export declare function instanceOfRoomDtoPagedResponse(value: object): value is RoomDtoPagedResponse;
export declare function RoomDtoPagedResponseFromJSON(json: any): RoomDtoPagedResponse;
export declare function RoomDtoPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomDtoPagedResponse;
export declare function RoomDtoPagedResponseToJSON(value?: RoomDtoPagedResponse | null): any;
