"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRoomDtoApiResponse = instanceOfRoomDtoApiResponse;
exports.RoomDtoApiResponseFromJSON = RoomDtoApiResponseFromJSON;
exports.RoomDtoApiResponseFromJSONTyped = RoomDtoApiResponseFromJSONTyped;
exports.RoomDtoApiResponseToJSON = RoomDtoApiResponseToJSON;
var RoomDto_1 = require("./RoomDto");
/**
 * Check if a given object implements the RoomDtoApiResponse interface.
 */
function instanceOfRoomDtoApiResponse(value) {
    return true;
}
function RoomDtoApiResponseFromJSON(json) {
    return RoomDtoApiResponseFromJSONTyped(json, false);
}
function RoomDtoApiResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : (0, RoomDto_1.RoomDtoFromJSON)(json['data']),
    };
}
function RoomDtoApiResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': (0, RoomDto_1.RoomDtoToJSON)(value['data']),
    };
}
