"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRoomParticipantDtoApiResponse = instanceOfRoomParticipantDtoApiResponse;
exports.RoomParticipantDtoApiResponseFromJSON = RoomParticipantDtoApiResponseFromJSON;
exports.RoomParticipantDtoApiResponseFromJSONTyped = RoomParticipantDtoApiResponseFromJSONTyped;
exports.RoomParticipantDtoApiResponseToJSON = RoomParticipantDtoApiResponseToJSON;
var RoomParticipantDto_1 = require("./RoomParticipantDto");
/**
 * Check if a given object implements the RoomParticipantDtoApiResponse interface.
 */
function instanceOfRoomParticipantDtoApiResponse(value) {
    return true;
}
function RoomParticipantDtoApiResponseFromJSON(json) {
    return RoomParticipantDtoApiResponseFromJSONTyped(json, false);
}
function RoomParticipantDtoApiResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : (0, RoomParticipantDto_1.RoomParticipantDtoFromJSON)(json['data']),
    };
}
function RoomParticipantDtoApiResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': (0, RoomParticipantDto_1.RoomParticipantDtoToJSON)(value['data']),
    };
}
