/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface RoomContentDto
 */
export interface RoomContentDto {
    /**
     *
     * @type {number}
     * @memberof RoomContentDto
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof RoomContentDto
     */
    title?: string | null;
    /**
     *
     * @type {string}
     * @memberof RoomContentDto
     */
    description?: string | null;
    /**
     *
     * @type {number}
     * @memberof RoomContentDto
     */
    order?: number;
    /**
     *
     * @type {number}
     * @memberof RoomContentDto
     */
    duration?: number;
    /**
     *
     * @type {Date}
     * @memberof RoomContentDto
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof RoomContentDto
     */
    updatedAt?: Date;
}
/**
 * Check if a given object implements the RoomContentDto interface.
 */
export declare function instanceOfRoomContentDto(value: object): value is RoomContentDto;
export declare function RoomContentDtoFromJSON(json: any): RoomContentDto;
export declare function RoomContentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomContentDto;
export declare function RoomContentDtoToJSON(value?: RoomContentDto | null): any;
