"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRoomParticipantDto = instanceOfRoomParticipantDto;
exports.RoomParticipantDtoFromJSON = RoomParticipantDtoFromJSON;
exports.RoomParticipantDtoFromJSONTyped = RoomParticipantDtoFromJSONTyped;
exports.RoomParticipantDtoToJSON = RoomParticipantDtoToJSON;
/**
 * Check if a given object implements the RoomParticipantDto interface.
 */
function instanceOfRoomParticipantDto(value) {
    return true;
}
function RoomParticipantDtoFromJSON(json) {
    return RoomParticipantDtoFromJSONTyped(json, false);
}
function RoomParticipantDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'isInterested': json['isInterested'] == null ? undefined : json['isInterested'],
        'attended': json['attended'] == null ? undefined : json['attended'],
        'attendedFromTime': json['attendedFromTime'] == null ? undefined : (new Date(json['attendedFromTime'])),
        'attendedToTime': json['attendedToTime'] == null ? undefined : (new Date(json['attendedToTime'])),
        'roomId': json['roomId'] == null ? undefined : json['roomId'],
        'socketId': json['socketId'] == null ? undefined : json['socketId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}
function RoomParticipantDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'isInterested': value['isInterested'],
        'attended': value['attended'],
        'attendedFromTime': value['attendedFromTime'] == null ? undefined : (value['attendedFromTime'].toISOString()),
        'attendedToTime': value['attendedToTime'] == null ? undefined : (value['attendedToTime'].toISOString()),
        'roomId': value['roomId'],
        'socketId': value['socketId'],
        'userId': value['userId'],
    };
}
