/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const RoomStatus: {
    readonly NUMBER_0: 0;
    readonly NUMBER_1: 1;
    readonly NUMBER_2: 2;
};
export type RoomStatus = typeof RoomStatus[keyof typeof RoomStatus];
export declare function instanceOfRoomStatus(value: any): boolean;
export declare function RoomStatusFromJSON(json: any): RoomStatus;
export declare function RoomStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomStatus;
export declare function RoomStatusToJSON(value?: RoomStatus | null): any;
