/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserSimplifiedDto } from './UserSimplifiedDto';
import type { RoomParticipant } from './RoomParticipant';
/**
 *
 * @export
 * @interface RoomDto
 */
export interface RoomDto {
    /**
     *
     * @type {number}
     * @memberof RoomDto
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof RoomDto
     */
    title?: string | null;
    /**
     *
     * @type {string}
     * @memberof RoomDto
     */
    description?: string | null;
    /**
     *
     * @type {any}
     * @memberof RoomDto
     */
    offers?: any | null;
    /**
     *
     * @type {Array<number>}
     * @memberof RoomDto
     */
    questionsCategories?: Array<number> | null;
    /**
     *
     * @type {string}
     * @memberof RoomDto
     */
    status?: string;
    /**
     *
     * @type {Date}
     * @memberof RoomDto
     */
    scheduledAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof RoomDto
     */
    finishedAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof RoomDto
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof RoomDto
     */
    updatedAt?: Date;
    /**
     *
     * @type {UserSimplifiedDto}
     * @memberof RoomDto
     */
    user?: UserSimplifiedDto;
    /**
     *
     * @type {Array<RoomParticipant>}
     * @memberof RoomDto
     */
    roomParticipants?: Array<RoomParticipant> | null;
}
/**
 * Check if a given object implements the RoomDto interface.
 */
export declare function instanceOfRoomDto(value: object): value is RoomDto;
export declare function RoomDtoFromJSON(json: any): RoomDto;
export declare function RoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomDto;
export declare function RoomDtoToJSON(value?: RoomDto | null): any;
