/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { RoomContentDto } from './RoomContentDto';
/**
 *
 * @export
 * @interface RoomContentDtoListApiResponse
 */
export interface RoomContentDtoListApiResponse {
    /**
     *
     * @type {number}
     * @memberof RoomContentDtoListApiResponse
     */
    statusCode?: number;
    /**
     *
     * @type {string}
     * @memberof RoomContentDtoListApiResponse
     */
    message?: string | null;
    /**
     *
     * @type {Array<RoomContentDto>}
     * @memberof RoomContentDtoListApiResponse
     */
    data?: Array<RoomContentDto> | null;
}
/**
 * Check if a given object implements the RoomContentDtoListApiResponse interface.
 */
export declare function instanceOfRoomContentDtoListApiResponse(value: object): value is RoomContentDtoListApiResponse;
export declare function RoomContentDtoListApiResponseFromJSON(json: any): RoomContentDtoListApiResponse;
export declare function RoomContentDtoListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomContentDtoListApiResponse;
export declare function RoomContentDtoListApiResponseToJSON(value?: RoomContentDtoListApiResponse | null): any;
