"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSimpleApiResponseApiResponse = instanceOfSimpleApiResponseApiResponse;
exports.SimpleApiResponseApiResponseFromJSON = SimpleApiResponseApiResponseFromJSON;
exports.SimpleApiResponseApiResponseFromJSONTyped = SimpleApiResponseApiResponseFromJSONTyped;
exports.SimpleApiResponseApiResponseToJSON = SimpleApiResponseApiResponseToJSON;
var SimpleApiResponse_1 = require("./SimpleApiResponse");
/**
 * Check if a given object implements the SimpleApiResponseApiResponse interface.
 */
function instanceOfSimpleApiResponseApiResponse(value) {
    return true;
}
function SimpleApiResponseApiResponseFromJSON(json) {
    return SimpleApiResponseApiResponseFromJSONTyped(json, false);
}
function SimpleApiResponseApiResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : (0, SimpleApiResponse_1.SimpleApiResponseFromJSON)(json['data']),
    };
}
function SimpleApiResponseApiResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': (0, SimpleApiResponse_1.SimpleApiResponseToJSON)(value['data']),
    };
}
