"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSimpleApiResponse = instanceOfSimpleApiResponse;
exports.SimpleApiResponseFromJSON = SimpleApiResponseFromJSON;
exports.SimpleApiResponseFromJSONTyped = SimpleApiResponseFromJSONTyped;
exports.SimpleApiResponseToJSON = SimpleApiResponseToJSON;
/**
 * Check if a given object implements the SimpleApiResponse interface.
 */
function instanceOfSimpleApiResponse(value) {
    return true;
}
function SimpleApiResponseFromJSON(json) {
    return SimpleApiResponseFromJSONTyped(json, false);
}
function SimpleApiResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
    };
}
function SimpleApiResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}
