/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SimpleApiResponse } from './SimpleApiResponse';
/**
 *
 * @export
 * @interface SimpleApiResponseApiResponse
 */
export interface SimpleApiResponseApiResponse {
    /**
     *
     * @type {number}
     * @memberof SimpleApiResponseApiResponse
     */
    statusCode?: number;
    /**
     *
     * @type {string}
     * @memberof SimpleApiResponseApiResponse
     */
    message?: string | null;
    /**
     *
     * @type {SimpleApiResponse}
     * @memberof SimpleApiResponseApiResponse
     */
    data?: SimpleApiResponse;
}
/**
 * Check if a given object implements the SimpleApiResponseApiResponse interface.
 */
export declare function instanceOfSimpleApiResponseApiResponse(value: object): value is SimpleApiResponseApiResponse;
export declare function SimpleApiResponseApiResponseFromJSON(json: any): SimpleApiResponseApiResponse;
export declare function SimpleApiResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleApiResponseApiResponse;
export declare function SimpleApiResponseApiResponseToJSON(value?: SimpleApiResponseApiResponse | null): any;
