/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringApiResponse
 */
export interface StringApiResponse {
    /**
     * 
     * @type {number}
     * @memberof StringApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof StringApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringApiResponse
     */
    data?: string | null;
}

/**
 * Check if a given object implements the StringApiResponse interface.
 */
export function instanceOfStringApiResponse(value: object): value is StringApiResponse {
    return true;
}

export function StringApiResponseFromJSON(json: any): StringApiResponse {
    return StringApiResponseFromJSONTyped(json, false);
}

export function StringApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function StringApiResponseToJSON(value?: StringApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': value['data'],
    };
}

