/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StringApiResponse
 */
export interface StringApiResponse {
    /**
     *
     * @type {number}
     * @memberof StringApiResponse
     */
    statusCode?: number;
    /**
     *
     * @type {string}
     * @memberof StringApiResponse
     */
    message?: string | null;
    /**
     *
     * @type {string}
     * @memberof StringApiResponse
     */
    data?: string | null;
}
/**
 * Check if a given object implements the StringApiResponse interface.
 */
export declare function instanceOfStringApiResponse(value: object): value is StringApiResponse;
export declare function StringApiResponseFromJSON(json: any): StringApiResponse;
export declare function StringApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringApiResponse;
export declare function StringApiResponseToJSON(value?: StringApiResponse | null): any;
