/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SystemQuestionDto
 */
export interface SystemQuestionDto {
    /**
     *
     * @type {number}
     * @memberof SystemQuestionDto
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof SystemQuestionDto
     */
    name?: string | null;
    /**
     *
     * @type {number}
     * @memberof SystemQuestionDto
     */
    categoryId?: number;
}
/**
 * Check if a given object implements the SystemQuestionDto interface.
 */
export declare function instanceOfSystemQuestionDto(value: object): value is SystemQuestionDto;
export declare function SystemQuestionDtoFromJSON(json: any): SystemQuestionDto;
export declare function SystemQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemQuestionDto;
export declare function SystemQuestionDtoToJSON(value?: SystemQuestionDto | null): any;
