"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSystemQuestionDto = instanceOfSystemQuestionDto;
exports.SystemQuestionDtoFromJSON = SystemQuestionDtoFromJSON;
exports.SystemQuestionDtoFromJSONTyped = SystemQuestionDtoFromJSONTyped;
exports.SystemQuestionDtoToJSON = SystemQuestionDtoToJSON;
/**
 * Check if a given object implements the SystemQuestionDto interface.
 */
function instanceOfSystemQuestionDto(value) {
    return true;
}
function SystemQuestionDtoFromJSON(json) {
    return SystemQuestionDtoFromJSONTyped(json, false);
}
function SystemQuestionDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}
function SystemQuestionDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'categoryId': value['categoryId'],
    };
}
