/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SystemQuestionDto } from './SystemQuestionDto';
/**
 *
 * @export
 * @interface SystemQuestionDtoListApiResponse
 */
export interface SystemQuestionDtoListApiResponse {
    /**
     *
     * @type {number}
     * @memberof SystemQuestionDtoListApiResponse
     */
    statusCode?: number;
    /**
     *
     * @type {string}
     * @memberof SystemQuestionDtoListApiResponse
     */
    message?: string | null;
    /**
     *
     * @type {Array<SystemQuestionDto>}
     * @memberof SystemQuestionDtoListApiResponse
     */
    data?: Array<SystemQuestionDto> | null;
}
/**
 * Check if a given object implements the SystemQuestionDtoListApiResponse interface.
 */
export declare function instanceOfSystemQuestionDtoListApiResponse(value: object): value is SystemQuestionDtoListApiResponse;
export declare function SystemQuestionDtoListApiResponseFromJSON(json: any): SystemQuestionDtoListApiResponse;
export declare function SystemQuestionDtoListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemQuestionDtoListApiResponse;
export declare function SystemQuestionDtoListApiResponseToJSON(value?: SystemQuestionDtoListApiResponse | null): any;
