/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { QuestionCategory } from './QuestionCategory';
/**
 *
 * @export
 * @interface SystemQuestion
 */
export interface SystemQuestion {
    /**
     *
     * @type {number}
     * @memberof SystemQuestion
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof SystemQuestion
     */
    name?: string | null;
    /**
     *
     * @type {number}
     * @memberof SystemQuestion
     */
    categoryId?: number;
    /**
     *
     * @type {QuestionCategory}
     * @memberof SystemQuestion
     */
    category?: QuestionCategory;
    /**
     *
     * @type {Date}
     * @memberof SystemQuestion
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof SystemQuestion
     */
    updatedAt?: Date;
}
/**
 * Check if a given object implements the SystemQuestion interface.
 */
export declare function instanceOfSystemQuestion(value: object): value is SystemQuestion;
export declare function SystemQuestionFromJSON(json: any): SystemQuestion;
export declare function SystemQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemQuestion;
export declare function SystemQuestionToJSON(value?: SystemQuestion | null): any;
