"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUpdateRoomParticipantDto = instanceOfUpdateRoomParticipantDto;
exports.UpdateRoomParticipantDtoFromJSON = UpdateRoomParticipantDtoFromJSON;
exports.UpdateRoomParticipantDtoFromJSONTyped = UpdateRoomParticipantDtoFromJSONTyped;
exports.UpdateRoomParticipantDtoToJSON = UpdateRoomParticipantDtoToJSON;
/**
 * Check if a given object implements the UpdateRoomParticipantDto interface.
 */
function instanceOfUpdateRoomParticipantDto(value) {
    return true;
}
function UpdateRoomParticipantDtoFromJSON(json) {
    return UpdateRoomParticipantDtoFromJSONTyped(json, false);
}
function UpdateRoomParticipantDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'isInterested': json['isInterested'] == null ? undefined : json['isInterested'],
        'attendedFromTime': json['attendedFromTime'] == null ? undefined : (new Date(json['attendedFromTime'])),
        'attendedToTime': json['attendedToTime'] == null ? undefined : (new Date(json['attendedToTime'])),
    };
}
function UpdateRoomParticipantDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'isInterested': value['isInterested'],
        'attendedFromTime': value['attendedFromTime'] == null ? undefined : (value['attendedFromTime'].toISOString()),
        'attendedToTime': value['attendedToTime'] == null ? undefined : (value['attendedToTime'].toISOString()),
    };
}
