"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUpdateSystemQuestionDto = instanceOfUpdateSystemQuestionDto;
exports.UpdateSystemQuestionDtoFromJSON = UpdateSystemQuestionDtoFromJSON;
exports.UpdateSystemQuestionDtoFromJSONTyped = UpdateSystemQuestionDtoFromJSONTyped;
exports.UpdateSystemQuestionDtoToJSON = UpdateSystemQuestionDtoToJSON;
/**
 * Check if a given object implements the UpdateSystemQuestionDto interface.
 */
function instanceOfUpdateSystemQuestionDto(value) {
    return true;
}
function UpdateSystemQuestionDtoFromJSON(json) {
    return UpdateSystemQuestionDtoFromJSONTyped(json, false);
}
function UpdateSystemQuestionDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'] == null ? undefined : json['name'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
    };
}
function UpdateSystemQuestionDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'categoryId': value['categoryId'],
    };
}
