/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserProfileLifeStyleDto
 */
export interface UserProfileLifeStyleDto {
    /**
     *
     * @type {number}
     * @memberof UserProfileLifeStyleDto
     */
    lifeStyleId?: number;
}
/**
 * Check if a given object implements the UserProfileLifeStyleDto interface.
 */
export declare function instanceOfUserProfileLifeStyleDto(value: object): value is UserProfileLifeStyleDto;
export declare function UserProfileLifeStyleDtoFromJSON(json: any): UserProfileLifeStyleDto;
export declare function UserProfileLifeStyleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileLifeStyleDto;
export declare function UserProfileLifeStyleDtoToJSON(value?: UserProfileLifeStyleDto | null): any;
