"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUser = instanceOfUser;
exports.UserFromJSON = UserFromJSON;
exports.UserFromJSONTyped = UserFromJSONTyped;
exports.UserToJSON = UserToJSON;
var UserProfile_1 = require("./UserProfile");
var RoomParticipant_1 = require("./RoomParticipant");
var Media_1 = require("./Media");
var Room_1 = require("./Room");
var Match_1 = require("./Match");
/**
 * Check if a given object implements the User interface.
 */
function instanceOfUser(value) {
    return true;
}
function UserFromJSON(json) {
    return UserFromJSONTyped(json, false);
}
function UserFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'normalizedUserName': json['normalizedUserName'] == null ? undefined : json['normalizedUserName'],
        'email': json['email'] == null ? undefined : json['email'],
        'normalizedEmail': json['normalizedEmail'] == null ? undefined : json['normalizedEmail'],
        'emailConfirmed': json['emailConfirmed'] == null ? undefined : json['emailConfirmed'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'securityStamp': json['securityStamp'] == null ? undefined : json['securityStamp'],
        'concurrencyStamp': json['concurrencyStamp'] == null ? undefined : json['concurrencyStamp'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'phoneNumberConfirmed': json['phoneNumberConfirmed'] == null ? undefined : json['phoneNumberConfirmed'],
        'twoFactorEnabled': json['twoFactorEnabled'] == null ? undefined : json['twoFactorEnabled'],
        'lockoutEnd': json['lockoutEnd'] == null ? undefined : (new Date(json['lockoutEnd'])),
        'lockoutEnabled': json['lockoutEnabled'] == null ? undefined : json['lockoutEnabled'],
        'accessFailedCount': json['accessFailedCount'] == null ? undefined : json['accessFailedCount'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'rooms': json['rooms'] == null ? undefined : (json['rooms'].map(Room_1.RoomFromJSON)),
        'roomParticipants': json['roomParticipants'] == null ? undefined : (json['roomParticipants'].map(RoomParticipant_1.RoomParticipantFromJSON)),
        'media': json['media'] == null ? undefined : (json['media'].map(Media_1.MediaFromJSON)),
        'userProfile': json['userProfile'] == null ? undefined : (0, UserProfile_1.UserProfileFromJSON)(json['userProfile']),
        'matchesAsUser1': json['matchesAsUser1'] == null ? undefined : (json['matchesAsUser1'].map(Match_1.MatchFromJSON)),
        'matchesAsUser2': json['matchesAsUser2'] == null ? undefined : (json['matchesAsUser2'].map(Match_1.MatchFromJSON)),
    };
}
function UserToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'userName': value['userName'],
        'normalizedUserName': value['normalizedUserName'],
        'email': value['email'],
        'normalizedEmail': value['normalizedEmail'],
        'emailConfirmed': value['emailConfirmed'],
        'passwordHash': value['passwordHash'],
        'securityStamp': value['securityStamp'],
        'concurrencyStamp': value['concurrencyStamp'],
        'phoneNumber': value['phoneNumber'],
        'phoneNumberConfirmed': value['phoneNumberConfirmed'],
        'twoFactorEnabled': value['twoFactorEnabled'],
        'lockoutEnd': value['lockoutEnd'] == null ? undefined : (value['lockoutEnd'].toISOString()),
        'lockoutEnabled': value['lockoutEnabled'],
        'accessFailedCount': value['accessFailedCount'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'rooms': value['rooms'] == null ? undefined : (value['rooms'].map(Room_1.RoomToJSON)),
        'roomParticipants': value['roomParticipants'] == null ? undefined : (value['roomParticipants'].map(RoomParticipant_1.RoomParticipantToJSON)),
        'media': value['media'] == null ? undefined : (value['media'].map(Media_1.MediaToJSON)),
        'userProfile': (0, UserProfile_1.UserProfileToJSON)(value['userProfile']),
        'matchesAsUser1': value['matchesAsUser1'] == null ? undefined : (value['matchesAsUser1'].map(Match_1.MatchToJSON)),
        'matchesAsUser2': value['matchesAsUser2'] == null ? undefined : (value['matchesAsUser2'].map(Match_1.MatchToJSON)),
    };
}
