/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileLifeStyleDto
 */
export interface UserProfileLifeStyleDto {
    /**
     * 
     * @type {number}
     * @memberof UserProfileLifeStyleDto
     */
    lifeStyleId?: number;
}

/**
 * Check if a given object implements the UserProfileLifeStyleDto interface.
 */
export function instanceOfUserProfileLifeStyleDto(value: object): value is UserProfileLifeStyleDto {
    return true;
}

export function UserProfileLifeStyleDtoFromJSON(json: any): UserProfileLifeStyleDto {
    return UserProfileLifeStyleDtoFromJSONTyped(json, false);
}

export function UserProfileLifeStyleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileLifeStyleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lifeStyleId': json['lifeStyleId'] == null ? undefined : json['lifeStyleId'],
    };
}

export function UserProfileLifeStyleDtoToJSON(value?: UserProfileLifeStyleDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lifeStyleId': value['lifeStyleId'],
    };
}

