"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserProfileLifeStyle = instanceOfUserProfileLifeStyle;
exports.UserProfileLifeStyleFromJSON = UserProfileLifeStyleFromJSON;
exports.UserProfileLifeStyleFromJSONTyped = UserProfileLifeStyleFromJSONTyped;
exports.UserProfileLifeStyleToJSON = UserProfileLifeStyleToJSON;
var UserProfile_1 = require("./UserProfile");
var LifeStyle_1 = require("./LifeStyle");
/**
 * Check if a given object implements the UserProfileLifeStyle interface.
 */
function instanceOfUserProfileLifeStyle(value) {
    return true;
}
function UserProfileLifeStyleFromJSON(json) {
    return UserProfileLifeStyleFromJSONTyped(json, false);
}
function UserProfileLifeStyleFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userProfileId': json['userProfileId'] == null ? undefined : json['userProfileId'],
        'lifeStyleId': json['lifeStyleId'] == null ? undefined : json['lifeStyleId'],
        'userProfile': json['userProfile'] == null ? undefined : (0, UserProfile_1.UserProfileFromJSON)(json['userProfile']),
        'lifeStyle': json['lifeStyle'] == null ? undefined : (0, LifeStyle_1.LifeStyleFromJSON)(json['lifeStyle']),
    };
}
function UserProfileLifeStyleToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'userProfileId': value['userProfileId'],
        'lifeStyleId': value['lifeStyleId'],
        'userProfile': (0, UserProfile_1.UserProfileToJSON)(value['userProfile']),
        'lifeStyle': (0, LifeStyle_1.LifeStyleToJSON)(value['lifeStyle']),
    };
}
