"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserApiResponse = instanceOfUserApiResponse;
exports.UserApiResponseFromJSON = UserApiResponseFromJSON;
exports.UserApiResponseFromJSONTyped = UserApiResponseFromJSONTyped;
exports.UserApiResponseToJSON = UserApiResponseToJSON;
var User_1 = require("./User");
/**
 * Check if a given object implements the UserApiResponse interface.
 */
function instanceOfUserApiResponse(value) {
    return true;
}
function UserApiResponseFromJSON(json) {
    return UserApiResponseFromJSONTyped(json, false);
}
function UserApiResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : (0, User_1.UserFromJSON)(json['data']),
    };
}
function UserApiResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': (0, User_1.UserToJSON)(value['data']),
    };
}
