/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserApiResponse
 */
export interface UserApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof UserApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {User}
     * @memberof UserApiResponse
     */
    data?: User;
}

/**
 * Check if a given object implements the UserApiResponse interface.
 */
export function instanceOfUserApiResponse(value: object): value is UserApiResponse {
    return true;
}

export function UserApiResponseFromJSON(json: any): UserApiResponse {
    return UserApiResponseFromJSONTyped(json, false);
}

export function UserApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UserFromJSON(json['data']),
    };
}

export function UserApiResponseToJSON(value?: UserApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': UserToJSON(value['data']),
    };
}

