/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileInterestDto
 */
export interface UserProfileInterestDto {
    /**
     * 
     * @type {number}
     * @memberof UserProfileInterestDto
     */
    interestId?: number;
}

/**
 * Check if a given object implements the UserProfileInterestDto interface.
 */
export function instanceOfUserProfileInterestDto(value: object): value is UserProfileInterestDto {
    return true;
}

export function UserProfileInterestDtoFromJSON(json: any): UserProfileInterestDto {
    return UserProfileInterestDtoFromJSONTyped(json, false);
}

export function UserProfileInterestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileInterestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'interestId': json['interestId'] == null ? undefined : json['interestId'],
    };
}

export function UserProfileInterestDtoToJSON(value?: UserProfileInterestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'interestId': value['interestId'],
    };
}

