/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileLifeStyleDto } from './UserProfileLifeStyleDto';
import {
    UserProfileLifeStyleDtoFromJSON,
    UserProfileLifeStyleDtoFromJSONTyped,
    UserProfileLifeStyleDtoToJSON,
} from './UserProfileLifeStyleDto';
import type { UserProfileInterestDto } from './UserProfileInterestDto';
import {
    UserProfileInterestDtoFromJSON,
    UserProfileInterestDtoFromJSONTyped,
    UserProfileInterestDtoToJSON,
} from './UserProfileInterestDto';

/**
 * 
 * @export
 * @interface UserProfileDto
 */
export interface UserProfileDto {
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    bio?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    relationshipGoal?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    education?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    zodiac?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    loveStyle?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<UserProfileInterestDto>}
     * @memberof UserProfileDto
     */
    userProfileInterests?: Array<UserProfileInterestDto> | null;
    /**
     * 
     * @type {Array<UserProfileLifeStyleDto>}
     * @memberof UserProfileDto
     */
    userProfileLifeStyles?: Array<UserProfileLifeStyleDto> | null;
}

/**
 * Check if a given object implements the UserProfileDto interface.
 */
export function instanceOfUserProfileDto(value: object): value is UserProfileDto {
    return true;
}

export function UserProfileDtoFromJSON(json: any): UserProfileDto {
    return UserProfileDtoFromJSONTyped(json, false);
}

export function UserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'height': json['height'] == null ? undefined : json['height'],
        'relationshipGoal': json['relationshipGoal'] == null ? undefined : json['relationshipGoal'],
        'education': json['education'] == null ? undefined : json['education'],
        'zodiac': json['zodiac'] == null ? undefined : json['zodiac'],
        'loveStyle': json['loveStyle'] == null ? undefined : json['loveStyle'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userProfileInterests': json['userProfileInterests'] == null ? undefined : ((json['userProfileInterests'] as Array<any>).map(UserProfileInterestDtoFromJSON)),
        'userProfileLifeStyles': json['userProfileLifeStyles'] == null ? undefined : ((json['userProfileLifeStyles'] as Array<any>).map(UserProfileLifeStyleDtoFromJSON)),
    };
}

export function UserProfileDtoToJSON(value?: UserProfileDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'bio': value['bio'],
        'height': value['height'],
        'relationshipGoal': value['relationshipGoal'],
        'education': value['education'],
        'zodiac': value['zodiac'],
        'loveStyle': value['loveStyle'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'userProfileInterests': value['userProfileInterests'] == null ? undefined : ((value['userProfileInterests'] as Array<any>).map(UserProfileInterestDtoToJSON)),
        'userProfileLifeStyles': value['userProfileLifeStyles'] == null ? undefined : ((value['userProfileLifeStyles'] as Array<any>).map(UserProfileLifeStyleDtoToJSON)),
    };
}

