"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserProfileInterestDto = instanceOfUserProfileInterestDto;
exports.UserProfileInterestDtoFromJSON = UserProfileInterestDtoFromJSON;
exports.UserProfileInterestDtoFromJSONTyped = UserProfileInterestDtoFromJSONTyped;
exports.UserProfileInterestDtoToJSON = UserProfileInterestDtoToJSON;
/**
 * Check if a given object implements the UserProfileInterestDto interface.
 */
function instanceOfUserProfileInterestDto(value) {
    return true;
}
function UserProfileInterestDtoFromJSON(json) {
    return UserProfileInterestDtoFromJSONTyped(json, false);
}
function UserProfileInterestDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'interestId': json['interestId'] == null ? undefined : json['interestId'],
    };
}
function UserProfileInterestDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'interestId': value['interestId'],
    };
}
