/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileDto } from './UserProfileDto';
import {
    UserProfileDtoFromJSON,
    UserProfileDtoFromJSONTyped,
    UserProfileDtoToJSON,
} from './UserProfileDto';

/**
 * 
 * @export
 * @interface UserProfileDtoApiResponse
 */
export interface UserProfileDtoApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserProfileDtoApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDtoApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {UserProfileDto}
     * @memberof UserProfileDtoApiResponse
     */
    data?: UserProfileDto;
}

/**
 * Check if a given object implements the UserProfileDtoApiResponse interface.
 */
export function instanceOfUserProfileDtoApiResponse(value: object): value is UserProfileDtoApiResponse {
    return true;
}

export function UserProfileDtoApiResponseFromJSON(json: any): UserProfileDtoApiResponse {
    return UserProfileDtoApiResponseFromJSONTyped(json, false);
}

export function UserProfileDtoApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDtoApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UserProfileDtoFromJSON(json['data']),
    };
}

export function UserProfileDtoApiResponseToJSON(value?: UserProfileDtoApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': UserProfileDtoToJSON(value['data']),
    };
}

