"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserProfile = instanceOfUserProfile;
exports.UserProfileFromJSON = UserProfileFromJSON;
exports.UserProfileFromJSONTyped = UserProfileFromJSONTyped;
exports.UserProfileToJSON = UserProfileToJSON;
var User_1 = require("./User");
var UserProfileLifeStyle_1 = require("./UserProfileLifeStyle");
var Gender_1 = require("./Gender");
var UserProfileInterest_1 = require("./UserProfileInterest");
/**
 * Check if a given object implements the UserProfile interface.
 */
function instanceOfUserProfile(value) {
    return true;
}
function UserProfileFromJSON(json) {
    return UserProfileFromJSONTyped(json, false);
}
function UserProfileFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'gender': json['gender'] == null ? undefined : (0, Gender_1.GenderFromJSON)(json['gender']),
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'placeToLive': json['placeToLive'] == null ? undefined : json['placeToLive'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'height': json['height'] == null ? undefined : json['height'],
        'relationshipGoal': json['relationshipGoal'] == null ? undefined : json['relationshipGoal'],
        'education': json['education'] == null ? undefined : json['education'],
        'zodiac': json['zodiac'] == null ? undefined : json['zodiac'],
        'loveStyle': json['loveStyle'] == null ? undefined : json['loveStyle'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userProfileInterests': json['userProfileInterests'] == null ? undefined : (json['userProfileInterests'].map(UserProfileInterest_1.UserProfileInterestFromJSON)),
        'userProfileLifeStyles': json['userProfileLifeStyles'] == null ? undefined : (json['userProfileLifeStyles'].map(UserProfileLifeStyle_1.UserProfileLifeStyleFromJSON)),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'user': json['user'] == null ? undefined : (0, User_1.UserFromJSON)(json['user']),
    };
}
function UserProfileToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'gender': (0, Gender_1.GenderToJSON)(value['gender']),
        'nationality': value['nationality'],
        'placeToLive': value['placeToLive'],
        'bio': value['bio'],
        'height': value['height'],
        'relationshipGoal': value['relationshipGoal'],
        'education': value['education'],
        'zodiac': value['zodiac'],
        'loveStyle': value['loveStyle'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'userProfileInterests': value['userProfileInterests'] == null ? undefined : (value['userProfileInterests'].map(UserProfileInterest_1.UserProfileInterestToJSON)),
        'userProfileLifeStyles': value['userProfileLifeStyles'] == null ? undefined : (value['userProfileLifeStyles'].map(UserProfileLifeStyle_1.UserProfileLifeStyleToJSON)),
        'userId': value['userId'],
        'user': (0, User_1.UserToJSON)(value['user']),
    };
}
