/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserProfile } from './UserProfile';
import type { RoomParticipant } from './RoomParticipant';
import type { Media } from './Media';
import type { Room } from './Room';
import type { Match } from './Match';
/**
 *
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {string}
     * @memberof User
     */
    id?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    userName?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    normalizedUserName?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    email?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    normalizedEmail?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof User
     */
    emailConfirmed?: boolean;
    /**
     *
     * @type {string}
     * @memberof User
     */
    passwordHash?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    securityStamp?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    concurrencyStamp?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    phoneNumber?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof User
     */
    phoneNumberConfirmed?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof User
     */
    twoFactorEnabled?: boolean;
    /**
     *
     * @type {Date}
     * @memberof User
     */
    lockoutEnd?: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof User
     */
    lockoutEnabled?: boolean;
    /**
     *
     * @type {number}
     * @memberof User
     */
    accessFailedCount?: number;
    /**
     *
     * @type {string}
     * @memberof User
     */
    firstName?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    lastName?: string | null;
    /**
     *
     * @type {Array<Room>}
     * @memberof User
     */
    rooms?: Array<Room> | null;
    /**
     *
     * @type {Array<RoomParticipant>}
     * @memberof User
     */
    roomParticipants?: Array<RoomParticipant> | null;
    /**
     *
     * @type {Array<Media>}
     * @memberof User
     */
    media?: Array<Media> | null;
    /**
     *
     * @type {UserProfile}
     * @memberof User
     */
    userProfile?: UserProfile;
    /**
     *
     * @type {Array<Match>}
     * @memberof User
     */
    matchesAsUser1?: Array<Match> | null;
    /**
     *
     * @type {Array<Match>}
     * @memberof User
     */
    matchesAsUser2?: Array<Match> | null;
}
/**
 * Check if a given object implements the User interface.
 */
export declare function instanceOfUser(value: object): value is User;
export declare function UserFromJSON(json: any): User;
export declare function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User;
export declare function UserToJSON(value?: User | null): any;
