"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserProfileLifeStyleDto = instanceOfUserProfileLifeStyleDto;
exports.UserProfileLifeStyleDtoFromJSON = UserProfileLifeStyleDtoFromJSON;
exports.UserProfileLifeStyleDtoFromJSONTyped = UserProfileLifeStyleDtoFromJSONTyped;
exports.UserProfileLifeStyleDtoToJSON = UserProfileLifeStyleDtoToJSON;
/**
 * Check if a given object implements the UserProfileLifeStyleDto interface.
 */
function instanceOfUserProfileLifeStyleDto(value) {
    return true;
}
function UserProfileLifeStyleDtoFromJSON(json) {
    return UserProfileLifeStyleDtoFromJSONTyped(json, false);
}
function UserProfileLifeStyleDtoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'lifeStyleId': json['lifeStyleId'] == null ? undefined : json['lifeStyleId'],
    };
}
function UserProfileLifeStyleDtoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'lifeStyleId': value['lifeStyleId'],
    };
}
