/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './UserDto';

/**
 * 
 * @export
 * @interface UserDtoApiResponse
 */
export interface UserDtoApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserDtoApiResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof UserDtoApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {UserDto}
     * @memberof UserDtoApiResponse
     */
    data?: UserDto;
}

/**
 * Check if a given object implements the UserDtoApiResponse interface.
 */
export function instanceOfUserDtoApiResponse(value: object): value is UserDtoApiResponse {
    return true;
}

export function UserDtoApiResponseFromJSON(json: any): UserDtoApiResponse {
    return UserDtoApiResponseFromJSONTyped(json, false);
}

export function UserDtoApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDtoApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UserDtoFromJSON(json['data']),
    };
}

export function UserDtoApiResponseToJSON(value?: UserDtoApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': UserDtoToJSON(value['data']),
    };
}

