/* tslint:disable */
/* eslint-disable */
/**
 * Dapp Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserLocation } from './UserLocation';
import {
    UserLocationFromJSON,
    UserLocationFromJSONTyped,
    UserLocationToJSON,
} from './UserLocation';
import type { SelectedDescriptor } from './SelectedDescriptor';
import {
    SelectedDescriptorFromJSON,
    SelectedDescriptorFromJSONTyped,
    SelectedDescriptorToJSON,
} from './SelectedDescriptor';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './Point';
import type { UserProfileGenderDto } from './UserProfileGenderDto';
import {
    UserProfileGenderDtoFromJSON,
    UserProfileGenderDtoFromJSONTyped,
    UserProfileGenderDtoToJSON,
} from './UserProfileGenderDto';

/**
 * 
 * @export
 * @interface UserProfileDto
 */
export interface UserProfileDto {
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    bio?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    ageFilterMax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    ageFilterMin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    distanceFilter?: number | null;
    /**
     * 
     * @type {Point}
     * @memberof UserProfileDto
     */
    pos?: Point;
    /**
     * 
     * @type {UserLocation}
     * @memberof UserProfileDto
     */
    location?: UserLocation;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    job?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    school?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDto
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    userId?: string | null;
    /**
     * 
     * @type {Array<SelectedDescriptor>}
     * @memberof UserProfileDto
     */
    selectedDescriptors?: Array<SelectedDescriptor> | null;
    /**
     * 
     * @type {Array<UserProfileGenderDto>}
     * @memberof UserProfileDto
     */
    userProfileGenders?: Array<UserProfileGenderDto> | null;
}

/**
 * Check if a given object implements the UserProfileDto interface.
 */
export function instanceOfUserProfileDto(value: object): value is UserProfileDto {
    return true;
}

export function UserProfileDtoFromJSON(json: any): UserProfileDto {
    return UserProfileDtoFromJSONTyped(json, false);
}

export function UserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'ageFilterMax': json['ageFilterMax'] == null ? undefined : json['ageFilterMax'],
        'ageFilterMin': json['ageFilterMin'] == null ? undefined : json['ageFilterMin'],
        'distanceFilter': json['distanceFilter'] == null ? undefined : json['distanceFilter'],
        'pos': json['pos'] == null ? undefined : PointFromJSON(json['pos']),
        'location': json['location'] == null ? undefined : UserLocationFromJSON(json['location']),
        'job': json['job'] == null ? undefined : json['job'],
        'school': json['school'] == null ? undefined : json['school'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'selectedDescriptors': json['selectedDescriptors'] == null ? undefined : ((json['selectedDescriptors'] as Array<any>).map(SelectedDescriptorFromJSON)),
        'userProfileGenders': json['userProfileGenders'] == null ? undefined : ((json['userProfileGenders'] as Array<any>).map(UserProfileGenderDtoFromJSON)),
    };
}

export function UserProfileDtoToJSON(value?: UserProfileDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'bio': value['bio'],
        'ageFilterMax': value['ageFilterMax'],
        'ageFilterMin': value['ageFilterMin'],
        'distanceFilter': value['distanceFilter'],
        'pos': PointToJSON(value['pos']),
        'location': UserLocationToJSON(value['location']),
        'job': value['job'],
        'school': value['school'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate'] as any).toISOString()),
        'userId': value['userId'],
        'selectedDescriptors': value['selectedDescriptors'] == null ? undefined : ((value['selectedDescriptors'] as Array<any>).map(SelectedDescriptorToJSON)),
        'userProfileGenders': value['userProfileGenders'] == null ? undefined : ((value['userProfileGenders'] as Array<any>).map(UserProfileGenderDtoToJSON)),
    };
}

